/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.fornecedor;

import controller.FornecedorController;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import model.Fornecedor;
import model.Requisito;
import util.BuscaCEP;
import util.CEP;
import util.SQL_URL;

/**
 *
 * @author KLEYN
 */
public class EditarFornecedor extends javax.swing.JFrame {

    private FornecedorController fornecedorController = null;
    private ArrayList<Requisito> listaRequisitos = null;
    private Fornecedor fornecedorAux = null;
    /**
     * Creates new form EditarFornecedor
     * @param fornecedorController
     * @param fornecedorAux
     */
    public EditarFornecedor(FornecedorController fornecedorController, Fornecedor fornecedorAux) {
        this.fornecedorController = fornecedorController;
        this.fornecedorAux = fornecedorAux;
        initComponents();
        this.setVisible(true);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.toFront();
        setagemInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel15 = new javax.swing.JPanel();
        campoCriacaoMotoristaCriacao2 = new javax.swing.JPanel();
        campoRazaoSocialFornecedor = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        campoNumeroCelularCriacaoFornecedor = new javax.swing.JFormattedTextField();
        jLabel75 = new javax.swing.JLabel();
        campoEnderecoFornecedor = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        campoNumeroEndFornecedor = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        campoComplementoFornecedor = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        campoBairroFornecedor = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        campoCEPFornecedor = new javax.swing.JFormattedTextField();
        campoCidadeFornecedor = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        campoEstadoFornecedor = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        campoEmailFornecedor = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jRadioButton_PF = new javax.swing.JRadioButton();
        jRadioButton_PJ = new javax.swing.JRadioButton();
        jLabel87 = new javax.swing.JLabel();
        campoNomeFantasiaFornecedor = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        campoCPF_CNPJFornecedor = new javax.swing.JFormattedTextField();
        jLabelCPF_CNPJCadastroFornecedor = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        campoResponsavelFornecedor = new javax.swing.JTextField();
        jLabel89 = new javax.swing.JLabel();
        campoNumeroTelefoneFornecedorCriacao = new javax.swing.JFormattedTextField();
        jLabel90 = new javax.swing.JLabel();
        campoObservacaoFornecedor = new javax.swing.JTextField();
        btnEdicaoFornecedor = new javax.swing.JButton();
        btnFecharCriacaoFornecedor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel15.setLayout(null);

        campoCriacaoMotoristaCriacao2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campoRazaoSocialFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoRazaoSocialFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoRazaoSocialFornecedorFocusLost(evt);
            }
        });
        campoRazaoSocialFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRazaoSocialFornecedorActionPerformed(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel68.setText("Razão Social *");

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel74.setText("Celular *");

        try {
            campoNumeroCelularCriacaoFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoNumeroCelularCriacaoFornecedor.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        campoNumeroCelularCriacaoFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoNumeroCelularCriacaoFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumeroCelularCriacaoFornecedorFocusLost(evt);
            }
        });

        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel75.setText("Endereço *");

        campoEnderecoFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoEnderecoFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEnderecoFornecedorFocusLost(evt);
            }
        });
        campoEnderecoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnderecoFornecedorActionPerformed(evt);
            }
        });

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel76.setText("Número *");

        campoNumeroEndFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoNumeroEndFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumeroEndFornecedorFocusLost(evt);
            }
        });

        jLabel77.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel77.setText("Complemento");

        campoComplementoFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoComplementoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoComplementoFornecedorActionPerformed(evt);
            }
        });

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel78.setText("Bairro *");

        campoBairroFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoBairroFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoBairroFornecedorFocusLost(evt);
            }
        });
        campoBairroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBairroFornecedorActionPerformed(evt);
            }
        });

        jLabel79.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel79.setText("CEP *");

        try {
            campoCEPFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCEPFornecedor.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        campoCEPFornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoCEPFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCEPFornecedorFocusLost(evt);
            }
        });
        campoCEPFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCEPFornecedorActionPerformed(evt);
            }
        });

        campoCidadeFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoCidadeFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCidadeFornecedorFocusLost(evt);
            }
        });
        campoCidadeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCidadeFornecedorActionPerformed(evt);
            }
        });

        jLabel80.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel80.setText("Cidade *");

        jLabel81.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel81.setText("Estado *");

        campoEstadoFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoEstadoFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEstadoFornecedorFocusLost(evt);
            }
        });
        campoEstadoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEstadoFornecedorActionPerformed(evt);
            }
        });

        jLabel82.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel82.setText("Email *");

        campoEmailFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoEmailFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEmailFornecedorFocusLost(evt);
            }
        });
        campoEmailFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailFornecedorActionPerformed(evt);
            }
        });

        jLabel83.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel83.setText("* Campos Obrigatórios");

        jLabel86.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel86.setText("Tipo de Fornecedor *");

        buttonGroup1.add(jRadioButton_PF);
        jRadioButton_PF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton_PF.setText("Física");
        jRadioButton_PF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_PFActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_PJ);
        jRadioButton_PJ.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton_PJ.setText("Jurídica");
        jRadioButton_PJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_PJActionPerformed(evt);
            }
        });

        jLabel87.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel87.setText("Nome Fantasia *");

        campoNomeFantasiaFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoNomeFantasiaFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNomeFantasiaFornecedorFocusLost(evt);
            }
        });
        campoNomeFantasiaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeFantasiaFornecedorActionPerformed(evt);
            }
        });

        jLabel88.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel88.setText("CPF/CNPJ *");

        try {
            campoCPF_CNPJFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCPF_CNPJFornecedor.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        campoCPF_CNPJFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCPF_CNPJFornecedorFocusLost(evt);
            }
        });
        campoCPF_CNPJFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCPF_CNPJFornecedorActionPerformed(evt);
            }
        });

        jLabelCPF_CNPJCadastroFornecedor.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelCPF_CNPJCadastroFornecedor.setForeground(new java.awt.Color(204, 0, 0));
        jLabelCPF_CNPJCadastroFornecedor.setText("Já cadastrado.");

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel69.setText("Responsável *");

        campoResponsavelFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoResponsavelFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoResponsavelFornecedorFocusLost(evt);
            }
        });
        campoResponsavelFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoResponsavelFornecedorActionPerformed(evt);
            }
        });

        jLabel89.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel89.setText("Telefone*");

        try {
            campoNumeroTelefoneFornecedorCriacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoNumeroTelefoneFornecedorCriacao.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        campoNumeroTelefoneFornecedorCriacao.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoNumeroTelefoneFornecedorCriacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumeroTelefoneFornecedorCriacaoFocusLost(evt);
            }
        });

        jLabel90.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel90.setText("Observações");

        campoObservacaoFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoObservacaoFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoObservacaoFornecedorFocusLost(evt);
            }
        });
        campoObservacaoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoObservacaoFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campoCriacaoMotoristaCriacao2Layout = new javax.swing.GroupLayout(campoCriacaoMotoristaCriacao2);
        campoCriacaoMotoristaCriacao2.setLayout(campoCriacaoMotoristaCriacao2Layout);
        campoCriacaoMotoristaCriacao2Layout.setHorizontalGroup(
            campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jRadioButton_PF)
                        .addGap(15, 15, 15)
                        .addComponent(jRadioButton_PJ))
                    .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                                .addComponent(campoResponsavelFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(campoNumeroTelefoneFornecedorCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(campoNumeroCelularCriacaoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(campoCEPFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoEnderecoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNumeroEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoComplementoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoBairroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoObservacaoFornecedor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                                        .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoCidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoEstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoRazaoSocialFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNomeFantasiaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCPF_CNPJCadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCPF_CNPJFornecedor))
                        .addGap(1, 1, 1)))
                .addGap(31, 31, 31))
        );
        campoCriacaoMotoristaCriacao2Layout.setVerticalGroup(
            campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel86)
                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_PF)
                    .addComponent(jRadioButton_PJ))
                .addGap(21, 21, 21)
                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                        .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel68)
                            .addComponent(jLabel88))
                        .addGap(6, 6, 6)
                        .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoRazaoSocialFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCPF_CNPJFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                        .addComponent(jLabel87)
                        .addGap(6, 6, 6)
                        .addComponent(campoNomeFantasiaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCPF_CNPJCadastroFornecedor)
                .addGap(7, 7, 7)
                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                        .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel69)
                            .addComponent(jLabel89)
                            .addComponent(jLabel74)
                            .addComponent(jLabel79))
                        .addGap(10, 10, 10)
                        .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoResponsavelFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNumeroTelefoneFornecedorCriacao, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(campoNumeroCelularCriacaoFornecedor)
                            .addComponent(campoCEPFornecedor))
                        .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel75)
                                .addGap(5, 5, 5)
                                .addComponent(campoEnderecoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                                        .addComponent(jLabel77)
                                        .addGap(4, 4, 4)
                                        .addComponent(campoComplementoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(campoBairroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoCriacaoMotoristaCriacao2Layout.createSequentialGroup()
                        .addComponent(jLabel76)
                        .addGap(4, 4, 4)
                        .addComponent(campoNumeroEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel81)
                        .addComponent(jLabel80))
                    .addComponent(jLabel82))
                .addGap(7, 7, 7)
                .addGroup(campoCriacaoMotoristaCriacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoCidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel90)
                .addGap(7, 7, 7)
                .addComponent(campoObservacaoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel83)
                .addGap(21, 21, 21))
        );

        campoCPF_CNPJFornecedor.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                try {
                    avisaCPF_CNPJFornecedor(campoCPF_CNPJFornecedor, jLabelCPF_CNPJCadastroFornecedor);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(EditarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(EditarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            public void removeUpdate(DocumentEvent e) {
                try {
                    avisaCPF_CNPJFornecedor(campoCPF_CNPJFornecedor, jLabelCPF_CNPJCadastroFornecedor);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(EditarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(EditarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            public void insertUpdate(DocumentEvent e) {
                try {
                    avisaCPF_CNPJFornecedor(campoCPF_CNPJFornecedor, jLabelCPF_CNPJCadastroFornecedor);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(EditarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(EditarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        jPanel15.add(campoCriacaoMotoristaCriacao2);
        campoCriacaoMotoristaCriacao2.setBounds(30, 80, 960, 470);

        btnEdicaoFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEdicaoFornecedor.setText("SALVAR");
        btnEdicaoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdicaoFornecedorActionPerformed(evt);
            }
        });
        btnEdicaoFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEdicaoFornecedorKeyPressed(evt);
            }
        });
        jPanel15.add(btnEdicaoFornecedor);
        btnEdicaoFornecedor.setBounds(860, 580, 130, 40);

        btnFecharCriacaoFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFecharCriacaoFornecedor.setText("FECHAR");
        btnFecharCriacaoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharCriacaoFornecedorActionPerformed(evt);
            }
        });
        btnFecharCriacaoFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnFecharCriacaoFornecedorKeyPressed(evt);
            }
        });
        jPanel15.add(btnFecharCriacaoFornecedor);
        btnFecharCriacaoFornecedor.setBounds(710, 580, 130, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("EDIÇÃO DE FORNECEDOR");
        jPanel15.add(jLabel1);
        jLabel1.setBounds(30, 30, 290, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoR.png"))); // NOI18N
        jPanel15.add(jLabel2);
        jLabel2.setBounds(30, 550, 510, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                    .addGap(19, 19, 19)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoRazaoSocialFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRazaoSocialFornecedorFocusLost
        if (campoRazaoSocialFornecedor.getText().equals("")) {
            getListaRequisitos().get(1).setIsOk(false);
        } else {
            getListaRequisitos().get(1).setIsOk(true);
        }
    }//GEN-LAST:event_campoRazaoSocialFornecedorFocusLost

    private void campoRazaoSocialFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRazaoSocialFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRazaoSocialFornecedorActionPerformed

    private void campoNumeroCelularCriacaoFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroCelularCriacaoFornecedorFocusLost
        if (campoNumeroCelularCriacaoFornecedor.getText().contains(" ")) {
            getListaRequisitos().get(6).setIsOk(false);
        } else {
            getListaRequisitos().get(6).setIsOk(true);
        }
    }//GEN-LAST:event_campoNumeroCelularCriacaoFornecedorFocusLost

    private void campoEnderecoFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEnderecoFornecedorFocusLost
        if (campoEnderecoFornecedor.getText().equals("")) {
            getListaRequisitos().get(8).setIsOk(false);
        } else {
            getListaRequisitos().get(8).setIsOk(true);
        }
    }//GEN-LAST:event_campoEnderecoFornecedorFocusLost

    private void campoEnderecoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEnderecoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEnderecoFornecedorActionPerformed

    private void campoNumeroEndFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroEndFornecedorFocusLost
        if (campoNumeroEndFornecedor.getText().equals("")) {
            getListaRequisitos().get(9).setIsOk(false);
        } else {
            getListaRequisitos().get(9).setIsOk(true);
        }
    }//GEN-LAST:event_campoNumeroEndFornecedorFocusLost

    private void campoComplementoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoComplementoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoComplementoFornecedorActionPerformed

    private void campoBairroFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoBairroFornecedorFocusLost
        if (campoBairroFornecedor.getText().equals("")) {
            getListaRequisitos().get(10).setIsOk(false);
        } else {
            getListaRequisitos().get(10).setIsOk(true);
        }
    }//GEN-LAST:event_campoBairroFornecedorFocusLost

    private void campoBairroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBairroFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBairroFornecedorActionPerformed

    private void campoCEPFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCEPFornecedorFocusLost
        if (campoCEPFornecedor.getText().contains(" ")) {
            getListaRequisitos().get(7).setIsOk(false);
        } else {
            getListaRequisitos().get(7).setIsOk(true);
            BuscaCEP buscaAux = new BuscaCEP();
            CEP cepAux;
            cepAux = buscaAux.buscarCep(campoCEPFornecedor.getText());
            campoEnderecoFornecedor.setText(cepAux.getLogradouro());
            campoBairroFornecedor.setText(cepAux.getBairro());
            campoCidadeFornecedor.setText(cepAux.getCidade());
            campoEstadoFornecedor.setText(cepAux.getUf());
            getListaRequisitos().get(8).setIsOk(true);
            getListaRequisitos().get(10).setIsOk(true);
            getListaRequisitos().get(11).setIsOk(true);
            getListaRequisitos().get(12).setIsOk(true);
        }
    }//GEN-LAST:event_campoCEPFornecedorFocusLost

    private void campoCEPFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCEPFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCEPFornecedorActionPerformed

    private void campoCidadeFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCidadeFornecedorFocusLost
        if (campoCidadeFornecedor.getText().equals("")) {
            getListaRequisitos().get(11).setIsOk(false);
        } else {
            getListaRequisitos().get(11).setIsOk(true);
        }
    }//GEN-LAST:event_campoCidadeFornecedorFocusLost

    private void campoCidadeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCidadeFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCidadeFornecedorActionPerformed

    private void campoEstadoFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEstadoFornecedorFocusLost
        if (campoEstadoFornecedor.getText().equals("")) {
            getListaRequisitos().get(12).setIsOk(false);
        } else {
            getListaRequisitos().get(12).setIsOk(true);
        }
    }//GEN-LAST:event_campoEstadoFornecedorFocusLost

    private void campoEstadoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEstadoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEstadoFornecedorActionPerformed

    private void campoEmailFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFornecedorFocusLost
        if (campoEmailFornecedor.getText().equals("")) {
            getListaRequisitos().get(13).setIsOk(false);
        } else {
            getListaRequisitos().get(13).setIsOk(true);
        }
    }//GEN-LAST:event_campoEmailFornecedorFocusLost

    private void campoEmailFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailFornecedorActionPerformed

    private void jRadioButton_PFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_PFActionPerformed
        if (jRadioButton_PF.isSelected()) {
            getListaRequisitos().get(0).setIsOk(true);
            campoCPF_CNPJFornecedor.setValue(null);
            MaskFormatter cpf = null;
            try {
                cpf = new MaskFormatter("###.###.###-##");
            } catch (ParseException ex) {
                Logger.getLogger(EditarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
            campoCPF_CNPJFornecedor.setFormatterFactory(new DefaultFormatterFactory(cpf));
        }
    }//GEN-LAST:event_jRadioButton_PFActionPerformed

    private void jRadioButton_PJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_PJActionPerformed
        if (jRadioButton_PJ.isSelected()) {
            getListaRequisitos().get(0).setIsOk(true);
            campoCPF_CNPJFornecedor.setValue(null);
            MaskFormatter cnpj = null;
            try {
                cnpj = new MaskFormatter("##.###.###/####-##");
            } catch (ParseException ex) {
                Logger.getLogger(EditarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
            campoCPF_CNPJFornecedor.setFormatterFactory(new DefaultFormatterFactory(cnpj));
        }
    }//GEN-LAST:event_jRadioButton_PJActionPerformed

    private void campoNomeFantasiaFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeFantasiaFornecedorFocusLost
        if (campoNomeFantasiaFornecedor.getText().equals("")) {
            getListaRequisitos().get(2).setIsOk(false);
        } else {
            getListaRequisitos().get(2).setIsOk(true);
        }
    }//GEN-LAST:event_campoNomeFantasiaFornecedorFocusLost

    private void campoNomeFantasiaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeFantasiaFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeFantasiaFornecedorActionPerformed

    private void campoCPF_CNPJFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPF_CNPJFornecedorFocusLost

    }//GEN-LAST:event_campoCPF_CNPJFornecedorFocusLost

    private void campoCPF_CNPJFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCPF_CNPJFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCPF_CNPJFornecedorActionPerformed

    private void campoResponsavelFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoResponsavelFornecedorFocusLost
        if (campoResponsavelFornecedor.getText().equals("")) {
            getListaRequisitos().get(4).setIsOk(false);
        } else {
            getListaRequisitos().get(4).setIsOk(true);
        }
    }//GEN-LAST:event_campoResponsavelFornecedorFocusLost

    private void campoResponsavelFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoResponsavelFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoResponsavelFornecedorActionPerformed

    private void campoNumeroTelefoneFornecedorCriacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroTelefoneFornecedorCriacaoFocusLost
        if (campoNumeroTelefoneFornecedorCriacao.getText().contains(" ")) {
            getListaRequisitos().get(5).setIsOk(false);
        } else {
            getListaRequisitos().get(5).setIsOk(true);
        }
    }//GEN-LAST:event_campoNumeroTelefoneFornecedorCriacaoFocusLost

    private void campoObservacaoFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoObservacaoFornecedorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_campoObservacaoFornecedorFocusLost

    private void campoObservacaoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoObservacaoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoObservacaoFornecedorActionPerformed

    private void btnEdicaoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdicaoFornecedorActionPerformed
        editarFornecedor();
    }//GEN-LAST:event_btnEdicaoFornecedorActionPerformed

    private void btnEdicaoFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEdicaoFornecedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            editarFornecedor();
        }
    }//GEN-LAST:event_btnEdicaoFornecedorKeyPressed

    private void btnFecharCriacaoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharCriacaoFornecedorActionPerformed
        fechaEditarFornecedor();
    }//GEN-LAST:event_btnFecharCriacaoFornecedorActionPerformed

    private void btnFecharCriacaoFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnFecharCriacaoFornecedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fechaEditarFornecedor();
        }
    }//GEN-LAST:event_btnFecharCriacaoFornecedorKeyPressed

    private final void setagemInicial(){
        setListaRequisitos(null);
        setListaRequisitos((ArrayList<Requisito>) new ArrayList());
        getListaRequisitos().add(new Requisito("Tipo de Fornecedor", true));
        getListaRequisitos().add(new Requisito("Razão Social", true));
        getListaRequisitos().add(new Requisito("Nome Fantasia", true));
        getListaRequisitos().add(new Requisito("CPF/CNPJ", true));
        getListaRequisitos().add(new Requisito("Responsável", true));
        getListaRequisitos().add(new Requisito("Telefone", true));
        getListaRequisitos().add(new Requisito("Celular", true));
        getListaRequisitos().add(new Requisito("CEP", true));
        getListaRequisitos().add(new Requisito("Endereço", true));
        getListaRequisitos().add(new Requisito("Número", true));
        getListaRequisitos().add(new Requisito("Bairro", true));
        getListaRequisitos().add(new Requisito("Cidade", true));
        getListaRequisitos().add(new Requisito("Estado", true));
        getListaRequisitos().add(new Requisito("Email", true));
        
        if (getFornecedorAux().getTipo().equals("F")){
            jRadioButton_PF.doClick();
        } else if (getFornecedorAux().getTipo().equals("J")){
            jRadioButton_PJ.doClick();
        }
        
        campoRazaoSocialFornecedor.setText(fornecedorAux.getRazao_Social());
        campoNomeFantasiaFornecedor.setText(fornecedorAux.getNome_Fantasia());
        campoCPF_CNPJFornecedor.setText(fornecedorAux.getCPF_CNPJ());
        campoResponsavelFornecedor.setText(fornecedorAux.getResponsavel());
        campoNumeroTelefoneFornecedorCriacao.setText(fornecedorAux.getTelefone());
        campoNumeroCelularCriacaoFornecedor.setText(fornecedorAux.getCelular());
        campoCEPFornecedor.setText(fornecedorAux.getCEP());
        campoEnderecoFornecedor.setText(fornecedorAux.getLogradouro());
        campoNumeroEndFornecedor.setText(fornecedorAux.getNumero());
        campoComplementoFornecedor.setText(fornecedorAux.getComplemento());
        campoBairroFornecedor.setText(fornecedorAux.getBairro());
        campoCidadeFornecedor.setText(fornecedorAux.getCidade());
        campoEstadoFornecedor.setText(fornecedorAux.getUF());
        campoEmailFornecedor.setText(fornecedorAux.getEmail());
        campoObservacaoFornecedor.setText(fornecedorAux.getObservacao());
    }
    
    private void avisaCPF_CNPJFornecedor(javax.swing.JFormattedTextField campoAux, javax.swing.JLabel labelAux) throws SQLException, ClassNotFoundException {
        if (jRadioButton_PF.isSelected()) {
            if (campoAux.getText().equals("   .   .   -  ")) {
                labelAux.setForeground(new java.awt.Color(212, 0, 51));
                labelAux.setText("Campo Vazio.");
                getListaRequisitos().get(3).setIsOk(false);
            } else {
                if (!campoAux.getText().contains(" ")) {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    String url = SQL_URL.getUrl();
                    try ( Connection con = DriverManager.getConnection(url)) {
                        String sql = "SELECT CPF_CNPJ FROM Fornecedor WHERE CPF_CNPJ = ?";
                        String textAux = campoAux.getText();
                        PreparedStatement pst = con.prepareStatement(sql);
                        pst.setString(1, textAux);
                        ResultSet rs = pst.executeQuery();
                        if (rs.next()) {
                            if (getFornecedorAux().getCPF_CNPJ().equals(textAux)) {
                                labelAux.setForeground(new java.awt.Color(51, 199, 9));
                                labelAux.setText("CPF original.");
                                getListaRequisitos().get(3).setIsOk(true);
                            } else {
                                labelAux.setForeground(new java.awt.Color(212, 0, 51));
                                labelAux.setText("CPF já cadastrado.");
                                getListaRequisitos().get(3).setIsOk(false);
                            }
                        } else {
                            labelAux.setForeground(new java.awt.Color(51, 199, 9));
                            labelAux.setText("CPF válido.");
                            getListaRequisitos().get(3).setIsOk(true);
                        }
                    }
                } else {
                    labelAux.setForeground(new java.awt.Color(212, 0, 51));
                    labelAux.setText("Valor inválido.");
                    getListaRequisitos().get(3).setIsOk(false);
                }
            }
        } else if (jRadioButton_PJ.isSelected()) {
            if (campoAux.getText().equals("  .   .   /    -  ")) {
                labelAux.setForeground(new java.awt.Color(212, 0, 51));
                labelAux.setText("Campo Vazio.");
                getListaRequisitos().get(3).setIsOk(false);
            } else {
                if (!campoAux.getText().contains(" ")) {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    String url = SQL_URL.getUrl();
                    try ( Connection con = DriverManager.getConnection(url)) {
                        String sql = "SELECT CPF_CNPJ FROM Fornecedor WHERE CPF_CNPJ = ?";
                        String textAux = campoAux.getText();
                        PreparedStatement pst = con.prepareStatement(sql);
                        pst.setString(1, textAux);
                        ResultSet rs = pst.executeQuery();
                        if (rs.next()) {
                            if (getFornecedorAux().getCPF_CNPJ().equals(textAux)) {
                                labelAux.setForeground(new java.awt.Color(51, 199, 9));
                                labelAux.setText("CNPJ original.");
                                getListaRequisitos().get(3).setIsOk(true);
                            } else {
                                labelAux.setForeground(new java.awt.Color(212, 0, 51));
                                labelAux.setText("CNPJ já cadastrado.");
                                getListaRequisitos().get(3).setIsOk(false);
                            }
                        } else {
                            labelAux.setForeground(new java.awt.Color(51, 199, 9));
                            labelAux.setText("CNPJ válido.");
                            getListaRequisitos().get(3).setIsOk(true);
                        }
                    }
                } else {
                    labelAux.setForeground(new java.awt.Color(212, 0, 51));
                    labelAux.setText("Valor inválido.");
                    getListaRequisitos().get(3).setIsOk(false);
                }
            }
        }
    }
    
    private void editarFornecedor(){
        Iterator<Requisito> iterador = listaRequisitos.iterator();
        String requisitosN = "";
        Requisito aux;
        boolean auxControl = true;
        while (iterador.hasNext()) {
            aux = iterador.next();
            if (!aux.isIsOk()) {
                requisitosN = requisitosN.concat(" " + aux.getRequisito() + ",");
                auxControl = false;
            }
        }
        if (!auxControl) {
            requisitosN = requisitosN.substring(0, requisitosN.length() - 1);
            JOptionPane.showMessageDialog(null, "Os seguintes requisitos não foram preeenchidos:" + requisitosN + ".");
        } else {
            String Razao_Social, Nome_Fantasia, Tipo, CPF_CNPJ, Telefone, Celular, Email, Responsavel, CEP, Logradouro, Numero,
                    Complemento, Bairro, Cidade, UF, Observacao;
            Razao_Social = campoRazaoSocialFornecedor.getText();
            Nome_Fantasia = campoNomeFantasiaFornecedor.getText();
            Tipo = "";
            if (jRadioButton_PF.isSelected()) {
                Tipo = "F";
            } else if (jRadioButton_PJ.isSelected()) {
                Tipo = "J";
            }
            CPF_CNPJ = campoCPF_CNPJFornecedor.getText();
            Telefone = campoNumeroTelefoneFornecedorCriacao.getText();
            Celular = campoNumeroCelularCriacaoFornecedor.getText();
            Email = campoEmailFornecedor.getText();
            Responsavel = campoResponsavelFornecedor.getText();
            CEP = campoCEPFornecedor.getText();
            Logradouro = campoEnderecoFornecedor.getText();
            Numero = campoNumeroEndFornecedor.getText();
            Complemento = campoComplementoFornecedor.getText();
            Bairro = campoBairroFornecedor.getText();
            Cidade = campoCidadeFornecedor.getText();
            UF = campoEstadoFornecedor.getText();
            Observacao = campoObservacaoFornecedor.getText();

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = SQL_URL.getUrl();
                try ( Connection con = DriverManager.getConnection(url)) {
                    String sql = "UPDATE Fornecedor SET Razao_Social = ?,Nome_Fantasia = ?,Tipo = ?,CPF_CNPJ = ?,Telefone = ?,Celular = ?,Email = ?,Responsavel = ?,CEP = ?,Logradouro = ?,Numero = ?,Complemento = ?,Bairro = ?,Cidade = ?,UF = ?,Observacao = ? WHERE CPF_CNPJ = ?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, Razao_Social);
                    pst.setString(2, Nome_Fantasia);
                    pst.setString(3, Tipo);
                    pst.setString(4, CPF_CNPJ);
                    pst.setString(5, Telefone);
                    pst.setString(6, Celular);
                    pst.setString(7, Email);
                    pst.setString(8, Responsavel);
                    pst.setString(9, CEP);
                    pst.setString(10, Logradouro);
                    pst.setString(11, Numero);
                    pst.setString(12, Complemento);
                    pst.setString(13, Bairro);
                    pst.setString(14, Cidade);
                    pst.setString(15, UF);
                    pst.setString(16, Observacao);
                    pst.setString(17, getFornecedorAux().getCPF_CNPJ());

                    pst.executeUpdate();
                    con.close();

                    JOptionPane.showMessageDialog(null, "Fornecedor '" + Nome_Fantasia + "' editado com sucesso.");
                    fornecedorController.fechaEdicaoFornecedor();
                }
            } catch (SQLException | HeadlessException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    
    private void fechaEditarFornecedor(){
        String message = "Deseja realmente cancelar a edição?";
        String title = "Cancelar Edição";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            fornecedorController.fechaEdicaoFornecedor();
        }
        if (reply == JOptionPane.NO_OPTION) {

        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdicaoFornecedor;
    private javax.swing.JButton btnFecharCriacaoFornecedor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoBairroFornecedor;
    private javax.swing.JFormattedTextField campoCEPFornecedor;
    private javax.swing.JFormattedTextField campoCPF_CNPJFornecedor;
    private javax.swing.JTextField campoCidadeFornecedor;
    private javax.swing.JTextField campoComplementoFornecedor;
    private javax.swing.JPanel campoCriacaoMotoristaCriacao2;
    private javax.swing.JTextField campoEmailFornecedor;
    private javax.swing.JTextField campoEnderecoFornecedor;
    private javax.swing.JTextField campoEstadoFornecedor;
    private javax.swing.JTextField campoNomeFantasiaFornecedor;
    private javax.swing.JFormattedTextField campoNumeroCelularCriacaoFornecedor;
    private javax.swing.JTextField campoNumeroEndFornecedor;
    private javax.swing.JFormattedTextField campoNumeroTelefoneFornecedorCriacao;
    private javax.swing.JTextField campoObservacaoFornecedor;
    private javax.swing.JTextField campoRazaoSocialFornecedor;
    private javax.swing.JTextField campoResponsavelFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabelCPF_CNPJCadastroFornecedor;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JRadioButton jRadioButton_PF;
    private javax.swing.JRadioButton jRadioButton_PJ;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fornecedorController
     */
    public FornecedorController getFornecedorController() {
        return fornecedorController;
    }

    /**
     * @param fornecedorController the fornecedorController to set
     */
    public void setFornecedorController(FornecedorController fornecedorController) {
        this.fornecedorController = fornecedorController;
    }

    /**
     * @return the listaRequisitos
     */
    public ArrayList<Requisito> getListaRequisitos() {
        return listaRequisitos;
    }

    /**
     * @param listaRequisitos the listaRequisitos to set
     */
    public void setListaRequisitos(ArrayList<Requisito> listaRequisitos) {
        this.listaRequisitos = listaRequisitos;
    }

    /**
     * @return the fornecedorAux
     */
    public Fornecedor getFornecedorAux() {
        return fornecedorAux;
    }

    /**
     * @param fornecedorAux the fornecedorAux to set
     */
    public void setFornecedorAux(Fornecedor fornecedorAux) {
        this.fornecedorAux = fornecedorAux;
    }
}
