/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import controller.EmprestimoController;
import controller.FornecedorController;
import controller.PecasController;
import controller.UsuarioController;
import controller.VeiculoController;
import javax.swing.JFrame;
import model.Cliente;
import model.Emprestimo;
import model.Fornecedor;
import model.Peca;
import model.Usuario;
import model.Veiculo;
import view.cliente.ClienteUI;
import view.emprestimo.EmprestimoUI;
import view.fornecedor.FornecedorUI;
import view.historico.AtualizacoesEstoque;
import view.peca.PecaUI;
import view.usuario.UsuarioUI;
import view.veiculo.VeiculoUI;

/**
 *
 * @author KLEYN
 */
public class Sistema_UI extends javax.swing.JFrame {
    
    private String loginCheck = null;
    private String nomeCheck = null;
    
    private PecasController pecasController = null;
    private UsuarioController usuarioController = null;
    private EmprestimoController emprestimoController = null;
    private VeiculoController veiculoController = null;
    private FornecedorController fornecedorController = null;
    private ClienteController clienteController = null;
    
    private Usuario usuarioAux = null;
    private Peca pecaAux = null;
    private Emprestimo emprestimoAux = null;
    private Veiculo veiculoAux = null;
    private Fornecedor fornecedorAux = null;
    private Cliente clienteAux = null;
    
    private UsuarioUI usuarioUI = null;
    private PecaUI pecaUI = null;
    private EmprestimoUI emprestimoUI =  null;
    private VeiculoUI veiculoUI = null;
    private FornecedorUI fornecedorUI = null;
    private ClienteUI clienteUI = null;
    
    private AtualizacoesEstoque attEstoque = null;
    
    /**
     * Creates new form Sistema_UI
     */
    public Sistema_UI() {
        this.usuarioController = new UsuarioController(this);
        this.pecasController = new PecasController(this);
        this.emprestimoController = new EmprestimoController(this);
        this.veiculoController = new VeiculoController(this);
        this.fornecedorController = new FornecedorController(this);
        initComponents();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        boxUsuario = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barraMenuADM = new javax.swing.JMenuBar();
        menuADM = new javax.swing.JMenu();
        menuADM_Usuario = new javax.swing.JMenuItem();
        menuADM_Fornecedor = new javax.swing.JMenuItem();
        menuADM_Pecas = new javax.swing.JMenuItem();
        menuADM_Veiculo = new javax.swing.JMenuItem();
        menuADM_Emprestimos = new javax.swing.JMenuItem();
        menuHIST = new javax.swing.JMenu();
        menuHIST_Estoque = new javax.swing.JMenuItem();
        menuOS = new javax.swing.JMenu();
        menuOS_Cadastro = new javax.swing.JMenuItem();
        menuOS_Acompanhamento = new javax.swing.JMenuItem();
        menuImportar = new javax.swing.JMenu();
        menuImportacao_Usuario = new javax.swing.JMenuItem();
        menuImportacao_Fornecedor = new javax.swing.JMenuItem();
        menuImportacao_Pecas = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuSair_Logoff = new javax.swing.JMenuItem();
        menuSair_Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        boxUsuario.setBackground(new java.awt.Color(227, 227, 227));
        boxUsuario.setColumns(20);
        boxUsuario.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        boxUsuario.setForeground(new java.awt.Color(0, 102, 0));
        boxUsuario.setRows(1);
        boxUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        boxUsuario.setDisabledTextColor(new java.awt.Color(0, 102, 51));
        boxUsuario.setEnabled(false);
        jScrollPane1.setViewportView(boxUsuario);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoR.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("SISTEMA DE GERENCIAMENTO OPERACIONAL");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simboloGrafico2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)))
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        barraMenuADM.setForeground(new java.awt.Color(0, 102, 0));
        barraMenuADM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraMenuADM.setName("barraMenuADM"); // NOI18N

        menuADM.setText("Administração");

        menuADM_Usuario.setText("Usuários");
        menuADM_Usuario.setBorderPainted(true);
        menuADM_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuADM_UsuarioActionPerformed(evt);
            }
        });
        menuADM.add(menuADM_Usuario);

        menuADM_Fornecedor.setText("Fornecedores");
        menuADM_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuADM_FornecedorActionPerformed(evt);
            }
        });
        menuADM.add(menuADM_Fornecedor);

        menuADM_Pecas.setText("Peças");
        menuADM_Pecas.setToolTipText("");
        menuADM_Pecas.setBorderPainted(true);
        menuADM_Pecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuADM_PecasActionPerformed(evt);
            }
        });
        menuADM.add(menuADM_Pecas);

        menuADM_Veiculo.setText("Veículos");
        menuADM_Veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuADM_VeiculoActionPerformed(evt);
            }
        });
        menuADM_Veiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menuADM_VeiculoKeyPressed(evt);
            }
        });
        menuADM.add(menuADM_Veiculo);

        menuADM_Emprestimos.setText("Emprestimos");
        menuADM_Emprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuADM_EmprestimosActionPerformed(evt);
            }
        });
        menuADM.add(menuADM_Emprestimos);

        barraMenuADM.add(menuADM);

        menuHIST.setText("Histórico");

        menuHIST_Estoque.setText("Atualizações do Estoque");
        menuHIST_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHIST_EstoqueActionPerformed(evt);
            }
        });
        menuHIST.add(menuHIST_Estoque);

        barraMenuADM.add(menuHIST);

        menuOS.setText("Ordem de Serviço");

        menuOS_Cadastro.setText("Cadastro");
        menuOS.add(menuOS_Cadastro);

        menuOS_Acompanhamento.setText("Acompanhamento");
        menuOS.add(menuOS_Acompanhamento);

        barraMenuADM.add(menuOS);

        menuImportar.setText("Importar Dados");

        menuImportacao_Usuario.setText("Usuário");
        menuImportar.add(menuImportacao_Usuario);

        menuImportacao_Fornecedor.setText("Fornecedor");
        menuImportar.add(menuImportacao_Fornecedor);

        menuImportacao_Pecas.setText("Peças");
        menuImportar.add(menuImportacao_Pecas);

        barraMenuADM.add(menuImportar);

        menuSair.setText("Sair");

        menuSair_Logoff.setText("Logoff");
        menuSair_Logoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSair_LogoffActionPerformed(evt);
            }
        });
        menuSair.add(menuSair_Logoff);

        menuSair_Sair.setText("Sair");
        menuSair_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSair_SairActionPerformed(evt);
            }
        });
        menuSair.add(menuSair_Sair);

        barraMenuADM.add(menuSair);

        setJMenuBar(barraMenuADM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1568, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuADM_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuADM_UsuarioActionPerformed
        //usuarioController.abreUsuarioUI();
    }//GEN-LAST:event_menuADM_UsuarioActionPerformed

    private void menuADM_PecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuADM_PecasActionPerformed
        getPecasController().abrePecaUI();
    }//GEN-LAST:event_menuADM_PecasActionPerformed

    private void menuSair_LogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSair_LogoffActionPerformed
        Login_UI loginUI = new Login_UI();
        loginUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuSair_LogoffActionPerformed

    private void menuSair_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSair_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSair_SairActionPerformed

    private void menuADM_EmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuADM_EmprestimosActionPerformed
        getEmprestimoController().abreEmprestimoUI();
    }//GEN-LAST:event_menuADM_EmprestimosActionPerformed

    private void menuADM_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuADM_FornecedorActionPerformed
        getFornecedorController().abreFornecedorUI();
    }//GEN-LAST:event_menuADM_FornecedorActionPerformed

    private void menuADM_VeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuADM_VeiculoActionPerformed
        getVeiculoController().abreVeiculoUI();
    }//GEN-LAST:event_menuADM_VeiculoActionPerformed

    private void menuADM_VeiculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuADM_VeiculoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuADM_VeiculoKeyPressed

    private void menuHIST_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHIST_EstoqueActionPerformed
        setAttEstoque(new AtualizacoesEstoque(this));
    }//GEN-LAST:event_menuHIST_EstoqueActionPerformed

    public void atualizaDados(){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenuADM;
    private javax.swing.JTextArea boxUsuario;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuADM;
    private javax.swing.JMenuItem menuADM_Emprestimos;
    private javax.swing.JMenuItem menuADM_Fornecedor;
    private javax.swing.JMenuItem menuADM_Pecas;
    private javax.swing.JMenuItem menuADM_Usuario;
    private javax.swing.JMenuItem menuADM_Veiculo;
    private javax.swing.JMenu menuHIST;
    private javax.swing.JMenuItem menuHIST_Estoque;
    private javax.swing.JMenuItem menuImportacao_Fornecedor;
    private javax.swing.JMenuItem menuImportacao_Pecas;
    private javax.swing.JMenuItem menuImportacao_Usuario;
    private javax.swing.JMenu menuImportar;
    private javax.swing.JMenu menuOS;
    private javax.swing.JMenuItem menuOS_Acompanhamento;
    private javax.swing.JMenuItem menuOS_Cadastro;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuSair_Logoff;
    private javax.swing.JMenuItem menuSair_Sair;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pecasController
     */
    public PecasController getPecasController() {
        return pecasController;
    }

    /**
     * @param pecasController the pecasController to set
     */
    public void setPecasController(PecasController pecasController) {
        this.pecasController = pecasController;
    }

    /**
     * @return the pecaAux
     */
    public Peca getPecaAux() {
        return pecaAux;
    }

    /**
     * @param pecaAux the pecaAux to set
     */
    public void setPecaAux(Peca pecaAux) {
        this.pecaAux = pecaAux;
    }

    /**
     * @return the pecaUI
     */
    public PecaUI getPecaUI() {
        return pecaUI;
    }

    /**
     * @param pecaUI the pecaUI to set
     */
    public void setPecaUI(PecaUI pecaUI) {
        this.pecaUI = pecaUI;
    }

    /**
     * @return the usuarioAux
     */
    public Usuario getUsuarioAux() {
        return usuarioAux;
    }

    /**
     * @param usuarioAux the usuarioAux to set
     */
    public void setUsuarioAux(Usuario usuarioAux) {
        this.usuarioAux = usuarioAux;
    }

    /**
     * @return the usuarioUI
     */
    public UsuarioUI getUsuarioUI() {
        return usuarioUI;
    }

    /**
     * @param usuarioUI the usuarioUI to set
     */
    public void setUsuarioUI(UsuarioUI usuarioUI) {
        this.usuarioUI = usuarioUI;
    }

    /**
     * @return the loginCheck
     */
    public String getLoginCheck() {
        return loginCheck;
    }

    /**
     * @param loginCheck the loginCheck to set
     */
    public void setLoginCheck(String loginCheck) {
        this.loginCheck = loginCheck;
    }

    /**
     * @return the nomeCheck
     */
    public String getNomeCheck() {
        return nomeCheck;
    }

    /**
     * @param nomeCheck the nomeCheck to set
     */
    public void setNomeCheck(String nomeCheck) {
        this.nomeCheck = nomeCheck;
    }

    /**
     * @return the usuarioController
     */
    public UsuarioController getUsuarioController() {
        return usuarioController;
    }

    /**
     * @param usuarioController the usuarioController to set
     */
    public void setUsuarioController(UsuarioController usuarioController) {
        this.usuarioController = usuarioController;
    }

    /**
     * @return the emprestimoController
     */
    public EmprestimoController getEmprestimoController() {
        return emprestimoController;
    }

    /**
     * @param emprestimoController the emprestimoController to set
     */
    public void setEmprestimoController(EmprestimoController emprestimoController) {
        this.emprestimoController = emprestimoController;
    }

    /**
     * @return the emprestimoAux
     */
    public Emprestimo getEmprestimoAux() {
        return emprestimoAux;
    }

    /**
     * @param emprestimoAux the emprestimoAux to set
     */
    public void setEmprestimoAux(Emprestimo emprestimoAux) {
        this.emprestimoAux = emprestimoAux;
    }

    /**
     * @return the emprestimoUI
     */
    public EmprestimoUI getEmprestimoUI() {
        return emprestimoUI;
    }

    /**
     * @param emprestimoUI the emprestimoUI to set
     */
    public void setEmprestimoUI(EmprestimoUI emprestimoUI) {
        this.emprestimoUI = emprestimoUI;
    }

    /**
     * @return the veiculoAux
     */
    public Veiculo getVeiculoAux() {
        return veiculoAux;
    }

    /**
     * @param veiculoAux the veiculoAux to set
     */
    public void setVeiculoAux(Veiculo veiculoAux) {
        this.veiculoAux = veiculoAux;
    }

    /**
     * @return the veiculoUI
     */
    public VeiculoUI getVeiculoUI() {
        return veiculoUI;
    }

    /**
     * @param veiculoUI the veiculoUI to set
     */
    public void setVeiculoUI(VeiculoUI veiculoUI) {
        this.veiculoUI = veiculoUI;
    }

    /**
     * @return the veiculoController
     */
    public VeiculoController getVeiculoController() {
        return veiculoController;
    }

    /**
     * @param veiculoController the veiculoController to set
     */
    public void setVeiculoController(VeiculoController veiculoController) {
        this.veiculoController = veiculoController;
    }

    /**
     * @return the fornecedorUI
     */
    public FornecedorUI getFornecedorUI() {
        return fornecedorUI;
    }

    /**
     * @param fornecedorUI the fornecedorUI to set
     */
    public void setFornecedorUI(FornecedorUI fornecedorUI) {
        this.fornecedorUI = fornecedorUI;
    }

    /**
     * @return the fornecedorController
     */
    public FornecedorController getFornecedorController() {
        return fornecedorController;
    }

    /**
     * @param fornecedorController the fornecedorController to set
     */
    public void setFornecedorController(FornecedorController fornecedorController) {
        this.fornecedorController = fornecedorController;
    }

    /**
     * @return the fornecedorAux
     */
    public Fornecedor getFornecedorAux() {
        return fornecedorAux;
    }

    /**
     * @param fornecedorAux the fornecedorAux to set
     */
    public void setFornecedorAux(Fornecedor fornecedorAux) {
        this.fornecedorAux = fornecedorAux;
    }

    /**
     * @return the attEstoque
     */
    public AtualizacoesEstoque getAttEstoque() {
        return attEstoque;
    }

    /**
     * @param attEstoque the attEstoque to set
     */
    public void setAttEstoque(AtualizacoesEstoque attEstoque) {
        this.attEstoque = attEstoque;
    }

    /**
     * @return the clienteController
     */
    public ClienteController getClienteController() {
        return clienteController;
    }

    /**
     * @param clienteController the clienteController to set
     */
    public void setClienteController(ClienteController clienteController) {
        this.clienteController = clienteController;
    }

    /**
     * @return the clienteAux
     */
    public Cliente getClienteAux() {
        return clienteAux;
    }

    /**
     * @param clienteAux the clienteAux to set
     */
    public void setClienteAux(Cliente clienteAux) {
        this.clienteAux = clienteAux;
    }

    /**
     * @return the clienteUI
     */
    public ClienteUI getClienteUI() {
        return clienteUI;
    }

    /**
     * @param clienteUI the clienteUI to set
     */
    public void setClienteUI(ClienteUI clienteUI) {
        this.clienteUI = clienteUI;
    }
}
