/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.peca;

import controller.PecasController;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.Format;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Requisito;
import util.SQL_URL;

/**
 *
 * @author KLEYN
 */
public class AtualizarEstoquePeca extends javax.swing.JFrame {
    
    private PecasController pecaController = null;
    private ArrayList<Requisito> listaRequisitos = null;
    
    /**
     * Creates new form AtualizarEstoquePeca
     * @param pecaController
     */
    public AtualizarEstoquePeca(PecasController pecaController) {
        this.pecaController = pecaController;
        initComponents();
        this.setVisible(true);
        setagemInicial();
        this.toFront();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        comboBoxProdutos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        campoNomeMotorista = new javax.swing.JTextField();
        campoCodigoPeca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoPrecoCompra = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        campoPrecoVenda = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        campoMarcaPeca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoModeloPeca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoAnoPeca = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        campoPorcentagemLucro = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        comboBoxFornecedor = new javax.swing.JComboBox<>();
        jLabel68 = new javax.swing.JLabel();
        campoRazaoSocialFornecedor = new javax.swing.JTextField();
        campoNomeFantasiaFornecedor = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        campoCPF_CNPJCadastroFornecedor = new javax.swing.JTextField();
        checkBoxAtualizaCV = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        campoPrecoCompra1 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        Format rateFormat = NumberFormat.getPercentInstance();
        campoPorcentagemLucro1 = new JFormattedTextField(rateFormat);
        jLabel13 = new javax.swing.JLabel();
        campoPrecoVenda1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        campoQuantidadeReposta = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        btnSalvarAumento = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        campoQuantidadeEstoque = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        campoQuantidadeRetirar = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        btnSalvarDiminuicao = new javax.swing.JButton();
        btnFechar1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        comboBoxProdutos1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        campoNomeMotorista1 = new javax.swing.JTextField();
        campoCodigoPeca1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        campoPrecoCompra2 = new javax.swing.JFormattedTextField();
        campoPorcentagemLucro2 = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        campoPrecoVenda2 = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        campoMarcaPeca1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        campoModeloPeca1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        campoAnoPeca1 = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        campoQuantidadeEstoque1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("ATUALIZAÇÃO DE ESTOQUE");

        jTabbedPane1.setBackground(new java.awt.Color(241, 241, 241));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));

        jPanel4.setBackground(new java.awt.Color(241, 241, 241));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("INFORMAÇÕES GERAIS");

        jPanel6.setBackground(new java.awt.Color(241, 241, 241));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comboBoxProdutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nome do Produto *");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Descrição");

        campoNomeMotorista.setEditable(false);
        campoNomeMotorista.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoNomeMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeMotoristaActionPerformed(evt);
            }
        });

        campoCodigoPeca.setEditable(false);
        campoCodigoPeca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Código");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Preço de Compra ");

        campoPrecoCompra.setEditable(false);
        campoPrecoCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        campoPrecoCompra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Porcentagem de Lucro ");

        campoPrecoVenda.setEditable(false);
        campoPrecoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        campoPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Preço de Venda ");

        campoMarcaPeca.setEditable(false);
        campoMarcaPeca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Marca");

        campoModeloPeca.setEditable(false);
        campoModeloPeca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Modelo");

        campoAnoPeca.setEditable(false);
        try {
            campoAnoPeca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoAnoPeca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Ano");

        campoPorcentagemLucro.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoMarcaPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoModeloPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoAnoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoCodigoPeca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(campoPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoPorcentagemLucro))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(comboBoxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCodigoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campoPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoPorcentagemLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMarcaPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25))
                    .addComponent(campoModeloPeca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoAnoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        comboBoxProdutos.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                carregaDadosProduto();
            }
        });

        jPanel7.setBackground(new java.awt.Color(241, 241, 241));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nome do Fornecedor *");

        comboBoxFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel68.setText("Razão Social ");

        campoRazaoSocialFornecedor.setEditable(false);
        campoRazaoSocialFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        campoNomeFantasiaFornecedor.setEditable(false);
        campoNomeFantasiaFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel87.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel87.setText("Nome Fantasia ");

        jLabel88.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel88.setText("CNPJ ");

        campoCPF_CNPJCadastroFornecedor.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoRazaoSocialFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNomeFantasiaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCPF_CNPJCadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(comboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(jLabel87)
                    .addComponent(jLabel88))
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCPF_CNPJCadastroFornecedor)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoNomeFantasiaFornecedor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoRazaoSocialFornecedor, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        comboBoxFornecedor.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                carregaDadosFornecedor();
            }
        });

        checkBoxAtualizaCV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBoxAtualizaCV.setText("Atualizar valor de Compra e Venda");
        checkBoxAtualizaCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAtualizaCVActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(241, 241, 241));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setEnabled(false);

        campoPrecoCompra1.setEditable(false);
        campoPrecoCompra1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        campoPrecoCompra1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoPrecoCompra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPrecoCompra1KeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Preço de Compra ");

        campoPorcentagemLucro1.setEditable(false);
        campoPorcentagemLucro1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        campoPorcentagemLucro1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoPorcentagemLucro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPorcentagemLucro1KeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Porcentagem de Lucro");

        campoPrecoVenda1.setEditable(false);
        campoPrecoVenda1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        campoPrecoVenda1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoPrecoVenda1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPrecoVenda1KeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Preço de Venda");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(campoPrecoCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoPorcentagemLucro1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(38, 38, 38)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPrecoVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoPrecoVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoPorcentagemLucro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPrecoCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        campoQuantidadeReposta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        campoQuantidadeReposta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoQuantidadeReposta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoQuantidadeRepostaFocusLost(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Quantidade Reposta:");

        btnSalvarAumento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvarAumento.setText("SALVAR");
        btnSalvarAumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAumentoActionPerformed(evt);
            }
        });
        btnSalvarAumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarAumentoKeyPressed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFechar.setText("FECHAR");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        btnFechar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnFecharKeyPressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Quantidade Estoque:");

        campoQuantidadeEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        campoQuantidadeEstoque.setEnabled(false);
        campoQuantidadeEstoque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBoxAtualizaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoQuantidadeReposta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvarAumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(checkBoxAtualizaCV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnSalvarAumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQuantidadeReposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        checkBoxAtualizaCV.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                if (checkBoxAtualizaCV.isSelected()){
                    campoPrecoCompra1.setEditable(true);
                    campoPorcentagemLucro1.setEditable(true);
                    campoPrecoVenda1.setEditable(true);
                    listaRequisitos.add(new Requisito("Preço de Compra", true));
                    listaRequisitos.add(new Requisito("Porcentagem de Lucro", true));
                    listaRequisitos.add(new Requisito("Preço de Venda", true));
                } else {
                    campoPrecoCompra1.setEditable(false);
                    campoPorcentagemLucro1.setEditable(false);
                    campoPrecoVenda1.setEditable(false);
                    Requisito aux;
                    aux = listaRequisitos.remove(3);
                    aux = listaRequisitos.remove(3);
                    aux = listaRequisitos.remove(3);
                    campoPrecoCompra1.setText("");
                    campoPorcentagemLucro1.setText("");
                    campoPrecoVenda1.setText("");
                }
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Abastecimento de Estoque", jPanel2);

        jPanel3.setBackground(new java.awt.Color(241, 241, 241));

        campoQuantidadeRetirar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        campoQuantidadeRetirar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoQuantidadeRetirar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoQuantidadeRetirarFocusLost(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText(" Quantidade a Retirar: *");

        btnSalvarDiminuicao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvarDiminuicao.setText("SALVAR");
        btnSalvarDiminuicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDiminuicaoActionPerformed(evt);
            }
        });
        btnSalvarDiminuicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarDiminuicaoKeyPressed(evt);
            }
        });

        btnFechar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFechar1.setText("FECHAR");
        btnFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar1ActionPerformed(evt);
            }
        });
        btnFechar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnFechar1KeyPressed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(241, 241, 241));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comboBoxProdutos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Nome do Produto *");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Descrição");

        campoNomeMotorista1.setEditable(false);
        campoNomeMotorista1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        campoNomeMotorista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeMotorista1ActionPerformed(evt);
            }
        });

        campoCodigoPeca1.setEditable(false);
        campoCodigoPeca1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Código");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Preço de Compra ");

        campoPrecoCompra2.setEditable(false);
        campoPrecoCompra2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        campoPrecoCompra2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        campoPorcentagemLucro2.setEditable(false);
        try {
            campoPorcentagemLucro2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoPorcentagemLucro2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Porcentagem de Lucro ");

        campoPrecoVenda2.setEditable(false);
        campoPrecoVenda2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        campoPrecoVenda2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Preço de Venda ");

        campoMarcaPeca1.setEditable(false);
        campoMarcaPeca1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Marca");

        campoModeloPeca1.setEditable(false);
        campoModeloPeca1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Modelo");

        campoAnoPeca1.setEditable(false);
        try {
            campoAnoPeca1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoAnoPeca1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Ano");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoMarcaPeca1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoModeloPeca1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoAnoPeca1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoCodigoPeca1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNomeMotorista1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(campoPrecoCompra2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(campoPorcentagemLucro2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoPrecoVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(comboBoxProdutos1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxProdutos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCodigoPeca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoPrecoVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoPorcentagemLucro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoPrecoCompra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomeMotorista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMarcaPeca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(25, 25, 25))
                    .addComponent(campoModeloPeca1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoAnoPeca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        comboBoxProdutos1.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                carregaDadosProduto1();
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Quantidade Estoque:");

        campoQuantidadeEstoque1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        campoQuantidadeEstoque1.setEnabled(false);
        campoQuantidadeEstoque1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoQuantidadeEstoque1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvarDiminuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoQuantidadeRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(315, 315, 315))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQuantidadeRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQuantidadeEstoque1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarDiminuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(228, 228, 228))
        );

        jTabbedPane1.addTab("Diminuir Estoque", jPanel3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(751, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        comboBoxProdutos1.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                carregaDadosProduto1();
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(870, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeMotoristaActionPerformed

    private void checkBoxAtualizaCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAtualizaCVActionPerformed
        if(checkBoxAtualizaCV.isSelected()){
            campoPrecoCompra1.setEnabled(true);
            campoPorcentagemLucro1.setEnabled(true);
            campoPrecoVenda1.setEnabled(true);
        } else {
            campoPrecoCompra1.setEnabled(false);
            campoPorcentagemLucro1.setEnabled(false);
            campoPrecoVenda1.setEnabled(false);
        }
    }//GEN-LAST:event_checkBoxAtualizaCVActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        fechaAtualizacao();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar1ActionPerformed
        fechaAtualizacao();
    }//GEN-LAST:event_btnFechar1ActionPerformed

    private void campoNomeMotorista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeMotorista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeMotorista1ActionPerformed

    private void btnSalvarDiminuicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDiminuicaoActionPerformed
        atualizaEstoqueDiminuicao();
    }//GEN-LAST:event_btnSalvarDiminuicaoActionPerformed

    private void btnFechar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnFechar1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fechaAtualizacao();
        }
    }//GEN-LAST:event_btnFechar1KeyPressed

    private void btnFecharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnFecharKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fechaAtualizacao();
        }
    }//GEN-LAST:event_btnFecharKeyPressed

    private void btnSalvarAumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAumentoActionPerformed
        atualizaEstoque();
    }//GEN-LAST:event_btnSalvarAumentoActionPerformed

    private void btnSalvarAumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarAumentoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            atualizaEstoque();
        }
    }//GEN-LAST:event_btnSalvarAumentoKeyPressed

    private void btnSalvarDiminuicaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarDiminuicaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            atualizaEstoqueDiminuicao();
        }
    }//GEN-LAST:event_btnSalvarDiminuicaoKeyPressed

    private void campoPrecoCompra1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPrecoCompra1KeyReleased
        if(!campoPrecoCompra1.getText().equals("") && !campoPorcentagemLucro1.getText().equals("")){
            String auxTemp = campoPrecoCompra1.getText().replaceAll("\\.","");
            auxTemp = auxTemp.replaceAll(",",".");
            String auxTemp2 = campoPorcentagemLucro1.getText().replaceAll("\\.","");
            auxTemp2 = auxTemp2.replaceAll(",",".");
            double resultado, precoCompra, porcentagem;
            precoCompra = Double.parseDouble(auxTemp);
            porcentagem = Double.parseDouble(auxTemp2);
            resultado = precoCompra * (1+(porcentagem/100));
            BigDecimal bd = new BigDecimal(resultado).setScale(3, RoundingMode.HALF_UP);
            String resultadoS = bd.doubleValue()+"";
            resultadoS = resultadoS.replaceAll("\\.",",");
            campoPrecoVenda1.setText(resultadoS);
            getListaRequisitos().get(4).setIsOk(true);
        } else if (!campoPrecoCompra1.getText().equals("") && !campoPrecoVenda1.getText().equals("")){
            String auxTemp = campoPrecoCompra1.getText().replaceAll("\\.","");
            auxTemp = auxTemp.replaceAll(",",".");
            String auxTemp2 = campoPrecoVenda1.getText().replaceAll("\\.","");
            auxTemp2 = auxTemp2.replaceAll(",",".");
            double resultado, precoCompra, precoVenda;
            precoCompra = Double.parseDouble(auxTemp);
            precoVenda = Double.parseDouble(auxTemp2);
            resultado = precoVenda - precoCompra;
            resultado = resultado / precoCompra;
            BigDecimal bd = new BigDecimal(resultado).setScale(3, RoundingMode.HALF_UP);
            String resultadoS = bd.doubleValue()+"";
            resultadoS = resultadoS.replaceAll("\\.",",");
            campoPorcentagemLucro1.setText(resultadoS);
            getListaRequisitos().get(3).setIsOk(true);
        }
    }//GEN-LAST:event_campoPrecoCompra1KeyReleased

    private void campoPorcentagemLucro1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPorcentagemLucro1KeyReleased
        if(!campoPorcentagemLucro1.getText().equals("") && !campoPrecoCompra1.getText().equals("")){
            String auxTemp = campoPorcentagemLucro1.getText().replaceAll("\\.","");
            auxTemp = auxTemp.replaceAll(",",".");
            String auxTemp2 = campoPrecoCompra1.getText().replaceAll("\\.","");
            auxTemp2 = auxTemp2.replaceAll(",",".");
            double resultado, precoCompra, porcentagem;
            precoCompra = Double.parseDouble(auxTemp2);
            porcentagem = Double.parseDouble(auxTemp);
            resultado = precoCompra * (1+(porcentagem/100));
            BigDecimal bd = new BigDecimal(resultado).setScale(3, RoundingMode.HALF_UP);
            String resultadoS = bd.doubleValue()+"";
            resultadoS = resultadoS.replaceAll("\\.",",");
            campoPrecoVenda1.setText(resultadoS);
            getListaRequisitos().get(4).setIsOk(true);
        } else if (!campoPorcentagemLucro1.getText().equals("") && !campoPrecoVenda1.getText().equals("")){
            String auxTemp = campoPorcentagemLucro1.getText().replaceAll("\\.","");
            auxTemp = auxTemp.replaceAll(",",".");
            String auxTemp2 = campoPrecoVenda1.getText().replaceAll("\\.","");
            auxTemp2 = auxTemp2.replaceAll(",",".");
            double resultado, porcentagem, precoVenda;
            porcentagem = Double.parseDouble(auxTemp);
            precoVenda = Double.parseDouble(auxTemp2);
            resultado = precoVenda / (1+(porcentagem/100));
            BigDecimal bd = new BigDecimal(resultado).setScale(3, RoundingMode.HALF_UP);
            String resultadoS = bd.doubleValue()+"";
            resultadoS = resultadoS.replaceAll("\\.",",");
            campoPrecoCompra1.setText(resultadoS);
            getListaRequisitos().get(2).setIsOk(true);
        }
    }//GEN-LAST:event_campoPorcentagemLucro1KeyReleased

    private void campoPrecoVenda1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPrecoVenda1KeyReleased
        if (!campoPrecoCompra1.getText().equals("") && !campoPrecoVenda1.getText().equals("")){
            String auxTemp = campoPrecoCompra1.getText().replaceAll("\\.","");
            auxTemp = auxTemp.replaceAll(",",".");
            String auxTemp2 = campoPrecoVenda1.getText().replaceAll("\\.","");
            auxTemp2 = auxTemp2.replaceAll(",",".");
            double resultado, precoCompra, precoVenda;
            precoCompra = Double.parseDouble(auxTemp);
            precoVenda = Double.parseDouble(auxTemp2);
            resultado = precoVenda - precoCompra;
            resultado = resultado / precoCompra;
            BigDecimal bd = new BigDecimal(resultado).setScale(3, RoundingMode.HALF_UP);
            String resultadoS = bd.doubleValue()+"";
            resultadoS = resultadoS.replaceAll("\\.",",");
            campoPorcentagemLucro1.setText(resultadoS);
            getListaRequisitos().get(3).setIsOk(true);
        } else if (!campoPorcentagemLucro1.getText().equals("") && !campoPrecoVenda1.getText().equals("")){
            String auxTemp = campoPorcentagemLucro1.getText().replaceAll("\\.","");
            auxTemp = auxTemp.replaceAll(",",".");
            String auxTemp2 = campoPrecoVenda1.getText().replaceAll("\\.","");
            auxTemp2 = auxTemp2.replaceAll(",",".");
            double resultado, porcentagem, precoVenda;
            porcentagem = Double.parseDouble(auxTemp);
            precoVenda = Double.parseDouble(auxTemp2);
            resultado = precoVenda / (1+(porcentagem/100));
            BigDecimal bd = new BigDecimal(resultado).setScale(3, RoundingMode.HALF_UP);
            String resultadoS = bd.doubleValue()+"";
            resultadoS = resultadoS.replaceAll("\\.",",");
            campoPrecoCompra1.setText(resultadoS);
            getListaRequisitos().get(2).setIsOk(true);
        }
    }//GEN-LAST:event_campoPrecoVenda1KeyReleased

    private void campoQuantidadeRepostaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoQuantidadeRepostaFocusLost
        if (campoQuantidadeReposta.getText().equals("")) {
            getListaRequisitos().get(2).setIsOk(false);
        } else {
            getListaRequisitos().get(2).setIsOk(true);
        }
    }//GEN-LAST:event_campoQuantidadeRepostaFocusLost

    private void campoQuantidadeRetirarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoQuantidadeRetirarFocusLost
        if (campoQuantidadeRetirar.getText().equals("")) {
            getListaRequisitos().get(2).setIsOk(false);
        } else {
            getListaRequisitos().get(2).setIsOk(true);
        }
    }//GEN-LAST:event_campoQuantidadeRetirarFocusLost

    
    private void atualizaEstoque(){
        Iterator<Requisito> iterador = listaRequisitos.iterator();
        String requisitosN = "";
        Requisito aux;
        boolean auxControl = true;
        while (iterador.hasNext()) {
            aux = iterador.next();
            if (!aux.isIsOk()) {
                requisitosN = requisitosN.concat(" " + aux.getRequisito() + ",");
                auxControl = false;
            }
        }
        if (!auxControl) {
            requisitosN = requisitosN.substring(0, requisitosN.length() - 1);
            JOptionPane.showMessageDialog(null, "Os seguintes requisitos não foram preeenchidos:" + requisitosN + ".");
        } else {
            int numEstoque = Integer.parseInt(campoQuantidadeEstoque.getText());
            int numAumentar = Integer.parseInt(campoQuantidadeReposta.getText());
            int resultado = numEstoque + numAumentar;

            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = SQL_URL.getUrl();
                try (Connection con = DriverManager.getConnection(url)) {
                    String sql = "UPDATE Produto SET QtdEstoque = ? WHERE Codigo = ?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, resultado+"");
                    pst.setString(2, campoCodigoPeca.getText());
                    ResultSet rs = pst.executeQuery();
                    if (rs.next()) {

                    }
                }
            } catch (SQLException e) {
                //JOptionPane.showMessageDialog(null,e);
            } catch (HeadlessException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
            String precoCompra, margemLucro, precoVenda;
            
            if (checkBoxAtualizaCV.isSelected()){
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String url = SQL_URL.getUrl();
                    try (Connection con = DriverManager.getConnection(url)) {
                        String sql = "UPDATE Produto SET PrecoCompra = ?, MargemLucro = ?, PrecoVenda = ? WHERE Codigo = ?";
                        PreparedStatement pst = con.prepareStatement(sql);
                        pst.setString(1, campoPrecoCompra1.getText());
                        pst.setString(2, campoPorcentagemLucro1.getText());
                        pst.setString(3, campoPrecoVenda1.getText());
                        pst.setString(4, campoCodigoPeca.getText());
                        ResultSet rs = pst.executeQuery();
                        if (rs.next()) {

                        }
                    }
                } catch (SQLException e) {
                    //JOptionPane.showMessageDialog(null,e);
                } catch (HeadlessException | ClassNotFoundException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                precoCompra = campoPrecoCompra1.getText();
                margemLucro = campoPorcentagemLucro1.getText();
                precoVenda = campoPrecoVenda1.getText();
            } else {
                precoCompra = campoPrecoCompra.getText();
                margemLucro = campoPorcentagemLucro.getText();
                precoVenda = campoPrecoVenda.getText();
            }
            
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = SQL_URL.getUrl();
                try (Connection con = DriverManager.getConnection(url)) {
                    String sql = "INSERT INTO AtualizacaoEstoque (CodigoProduto ,CNPJFornecedor,PrecoCompra,PorcentagemLucro,PrecoVenda,QuantidadeReposta) VALUES (?,?,?,?,?,?)";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, campoCodigoPeca.getText());
                    pst.setString(2, campoCPF_CNPJCadastroFornecedor.getText());
                    pst.setString(3, precoCompra);
                    pst.setString(4, margemLucro);
                    pst.setString(5, precoVenda);
                    pst.setString(6, numAumentar+"");

                    ResultSet rs = pst.executeQuery();
                    
                    if(rs.next()){
                        // FAZ NADA
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Produto '" + campoNomeMotorista.getText() + "' atualizado com sucesso.");
                //JOptionPane.showMessageDialog(null,e);
                pecaController.fechaAtualizacaoEstoque();
            } catch (HeadlessException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }
    
    private void atualizaEstoqueDiminuicao(){
        int numEstoque = Integer.parseInt(campoQuantidadeEstoque1.getText());
        int numDiminuir = Integer.parseInt(campoQuantidadeRetirar.getText());
        if (numDiminuir > numEstoque){
            JOptionPane.showMessageDialog(null, "Não é possível diminuir o estoque para um valor menor que 0.");
        } else {
            int resultado = numEstoque - numDiminuir;
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = SQL_URL.getUrl();
                try (Connection con = DriverManager.getConnection(url)) {
                    String sql = "UPDATE Produto SET QtdEstoque = ? WHERE Codigo = ?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, resultado+"");
                    pst.setString(2, campoCodigoPeca1.getText());
                    ResultSet rs = pst.executeQuery();
                    if (rs.next()) {
                        
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Produto '" + campoNomeMotorista1.getText() + "' atualizado com sucesso.");
                //JOptionPane.showMessageDialog(null,e);
                pecaController.fechaAtualizacaoEstoque();
            } catch (HeadlessException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
            } 
        }
    }
    
    
    private void fechaAtualizacao(){
        String message = "Deseja realmente cancelar a atualização?";
        String title = "Cancelar Atualização";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            pecaController.fechaAtualizacaoEstoque();
        }
        if (reply == JOptionPane.NO_OPTION) {

        }
    }
    
    public final void setagemInicial(){
        listaRequisitos = null;
        listaRequisitos = new ArrayList();
        
        listaRequisitos.add(new Requisito("Produto", false));
        listaRequisitos.add(new Requisito("Fornecedor", false));
        listaRequisitos.add(new Requisito("Quantidade para Atualização", false));
        
        setaDadosProduto();
        setaDadosFornecedor();
        
        setaDadosProduto1();
        
    }
    
    private void setaDadosProduto(){
        comboBoxProdutos.removeAllItems();
        comboBoxProdutos.addItem("Selecione");
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT Descricao FROM Produto";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String produtoAux = rs.getString("Descricao");
                    comboBoxProdutos.addItem(produtoAux);
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void setaDadosProduto1(){
        comboBoxProdutos1.removeAllItems();
        comboBoxProdutos1.addItem("Selecione");
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT Descricao FROM Produto";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String produtoAux = rs.getString("Descricao");
                    comboBoxProdutos1.addItem(produtoAux);
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void setaDadosFornecedor(){
        comboBoxFornecedor.removeAllItems();
        comboBoxFornecedor.addItem("Selecione");
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT Nome_Fantasia, CPF_CNPJ FROM Fornecedor";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String fornecedorAux = rs.getString("CPF_CNPJ") + " | " + rs.getString("Nome_Fantasia");
                    comboBoxFornecedor.addItem(fornecedorAux);
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void carregaDadosProduto(){
        if (comboBoxProdutos.getItemCount() > 0){
            String palavraBusca = (String)comboBoxProdutos.getSelectedItem(); 
            if (!palavraBusca.equals("Selecione")){
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String url = SQL_URL.getUrl();
                    try (Connection con = DriverManager.getConnection(url)) {
                        String sql = "SELECT Codigo, Descricao, PrecoCompra, MargemLucro, PrecoVenda, Marca, Modelo, Ano, QtdEstoque FROM Produto WHERE Descricao = ?";
                        PreparedStatement pst = con.prepareStatement(sql);
                        pst.setString(1, palavraBusca);
                        ResultSet rs = pst.executeQuery();
                        while (rs.next()) {
                            campoCodigoPeca.setText(rs.getString("Codigo"));
                            campoNomeMotorista.setText(rs.getString("Descricao"));
                            campoPrecoCompra.setText(rs.getString("PrecoCompra"));
                            campoPorcentagemLucro.setText(rs.getString("MargemLucro"));
                            campoPrecoVenda.setText(rs.getString("PrecoVenda"));
                            campoMarcaPeca.setText(rs.getString("Marca"));
                            campoModeloPeca.setText(rs.getString("Modelo"));
                            campoAnoPeca.setText(rs.getString("Ano"));
                            campoQuantidadeEstoque.setText(rs.getString("QtdEstoque"));
                            listaRequisitos.get(0).setIsOk(true);
                        }
                    }
                } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } else if (palavraBusca.equals("Selecione")){
                campoCodigoPeca.setText("");
                campoNomeMotorista.setText("");
                campoPrecoCompra.setText("");
                campoPorcentagemLucro.setText("");
                campoPrecoVenda.setText("");
                campoMarcaPeca.setText("");
                campoModeloPeca.setText("");
                campoAnoPeca.setText("");
                campoQuantidadeEstoque.setText("");
                listaRequisitos.get(0).setIsOk(false);
            }
        }
    }
    
    private void carregaDadosProduto1(){
        if (comboBoxProdutos1.getItemCount() > 0){
            String palavraBusca = (String)comboBoxProdutos1.getSelectedItem();
            if (!palavraBusca.equals("Selecione")){
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String url = SQL_URL.getUrl();
                    try (Connection con = DriverManager.getConnection(url)) {
                        String sql = "SELECT Codigo, Descricao, PrecoCompra, MargemLucro, PrecoVenda, Marca, Modelo, Ano, QtdEstoque FROM Produto WHERE Descricao = ?";
                        PreparedStatement pst = con.prepareStatement(sql);
                        pst.setString(1, palavraBusca);
                        ResultSet rs = pst.executeQuery();
                        while (rs.next()) {
                            campoCodigoPeca1.setText(rs.getString("Codigo"));
                            campoNomeMotorista1.setText(rs.getString("Descricao"));
                            campoPrecoCompra2.setText(rs.getString("PrecoCompra"));
                            campoPorcentagemLucro2.setText(rs.getString("MargemLucro"));
                            campoPrecoVenda2.setText(rs.getString("PrecoVenda"));
                            campoMarcaPeca1.setText(rs.getString("Marca"));
                            campoModeloPeca1.setText(rs.getString("Modelo"));
                            campoAnoPeca1.setText(rs.getString("Ano"));
                            campoQuantidadeEstoque1.setText(rs.getString("QtdEstoque"));
                            listaRequisitos.get(0).setIsOk(true);
                            listaRequisitos.get(1).setIsOk(true);
                        }
                    }
                } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } else if (palavraBusca.equals("Selecione")){
                campoCodigoPeca1.setText("");
                campoNomeMotorista1.setText("");
                campoPrecoCompra2.setText("");
                campoPorcentagemLucro2.setText("");
                campoPrecoVenda2.setText("");
                campoMarcaPeca1.setText("");
                campoModeloPeca1.setText("");
                campoAnoPeca1.setText("");
                campoQuantidadeEstoque1.setText("");
                listaRequisitos.get(0).setIsOk(false);
                listaRequisitos.get(1).setIsOk(false);
            }
        }   
    }
    
    private void carregaDadosFornecedor(){
        if (comboBoxFornecedor.getItemCount() > 0){
            String palavraBusca = (String)comboBoxFornecedor.getSelectedItem();
            if (!palavraBusca.equals("Selecione")){            
                String palavraBuscaAux = palavraBusca.substring(0, 18);
                String palavraBuscaAux2 = palavraBusca.substring(0, 14);
                Pattern j = Pattern.compile("[0-9]{2}.[0-9]{3}.[0-9]{3}/[0-9]{4}-[0-9]{2}");
                Pattern f = Pattern.compile("[0-9]{3}.[0-9]{3}.[0-9]{3}-[0-9]{2}");
                Matcher m1 = j.matcher(palavraBuscaAux);
                Matcher m2 = f.matcher(palavraBuscaAux2);

                if (m1.matches()){
                    palavraBusca = palavraBuscaAux;
                } else if (m2.matches()){
                    palavraBusca = palavraBuscaAux2;
                }
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String url = SQL_URL.getUrl();
                    try (Connection con = DriverManager.getConnection(url)) {
                        String sql = "SELECT Razao_Social, Nome_Fantasia, CPF_CNPJ FROM Fornecedor WHERE CPF_CNPJ = ?";
                        PreparedStatement pst = con.prepareStatement(sql);
                        pst.setString(1, palavraBusca);
                        ResultSet rs = pst.executeQuery();
                        while (rs.next()) {
                            campoRazaoSocialFornecedor.setText(rs.getString("Razao_Social"));
                            campoNomeFantasiaFornecedor.setText(rs.getString("Nome_Fantasia"));
                            campoCPF_CNPJCadastroFornecedor.setText(rs.getString("CPF_CNPJ"));
                            listaRequisitos.get(1).setIsOk(true);
                        }
                    }
                } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } else if (palavraBusca.equals("Selecione")){
                campoRazaoSocialFornecedor.setText("");
                campoNomeFantasiaFornecedor.setText("");
                campoCPF_CNPJCadastroFornecedor.setText("");
                listaRequisitos.get(1).setIsOk(false);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarEstoquePeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFechar1;
    private javax.swing.JButton btnSalvarAumento;
    private javax.swing.JButton btnSalvarDiminuicao;
    private javax.swing.JFormattedTextField campoAnoPeca;
    private javax.swing.JFormattedTextField campoAnoPeca1;
    private javax.swing.JTextField campoCPF_CNPJCadastroFornecedor;
    private javax.swing.JTextField campoCodigoPeca;
    private javax.swing.JTextField campoCodigoPeca1;
    private javax.swing.JTextField campoMarcaPeca;
    private javax.swing.JTextField campoMarcaPeca1;
    private javax.swing.JTextField campoModeloPeca;
    private javax.swing.JTextField campoModeloPeca1;
    private javax.swing.JTextField campoNomeFantasiaFornecedor;
    private javax.swing.JTextField campoNomeMotorista;
    private javax.swing.JTextField campoNomeMotorista1;
    private javax.swing.JTextField campoPorcentagemLucro;
    private javax.swing.JFormattedTextField campoPorcentagemLucro1;
    private javax.swing.JFormattedTextField campoPorcentagemLucro2;
    private javax.swing.JFormattedTextField campoPrecoCompra;
    private javax.swing.JFormattedTextField campoPrecoCompra1;
    private javax.swing.JFormattedTextField campoPrecoCompra2;
    private javax.swing.JFormattedTextField campoPrecoVenda;
    private javax.swing.JFormattedTextField campoPrecoVenda1;
    private javax.swing.JFormattedTextField campoPrecoVenda2;
    private javax.swing.JFormattedTextField campoQuantidadeEstoque;
    private javax.swing.JFormattedTextField campoQuantidadeEstoque1;
    private javax.swing.JFormattedTextField campoQuantidadeReposta;
    private javax.swing.JFormattedTextField campoQuantidadeRetirar;
    private javax.swing.JTextField campoRazaoSocialFornecedor;
    private javax.swing.JCheckBox checkBoxAtualizaCV;
    private javax.swing.JComboBox<String> comboBoxFornecedor;
    private javax.swing.JComboBox<String> comboBoxProdutos;
    private javax.swing.JComboBox<String> comboBoxProdutos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the listaRequisitos
     */
    public ArrayList<Requisito> getListaRequisitos() {
        return listaRequisitos;
    }

    /**
     * @param listaRequisitos the listaRequisitos to set
     */
    public void setListaRequisitos(ArrayList<Requisito> listaRequisitos) {
        this.listaRequisitos = listaRequisitos;
    }

    /**
     * @return the pecaController
     */
    public PecasController getPecaController() {
        return pecaController;
    }

    /**
     * @param pecaController the pecaController to set
     */
    public void setPecaController(PecasController pecaController) {
        this.pecaController = pecaController;
    }
}
