/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.peca;

import controller.PecasController;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Especificacao;
import model.Peca;
import util.SQL_URL;

/**
 *
 * @author KLEYN
 */
public class PecaUI extends javax.swing.JFrame {
    
    private Peca pecaAux = null;
    private CriarPeca criarPeca= null;
    private EditarPeca editarPeca = null;
    private VisualizarPeca visualizarPeca = null;
    
    private PecasController pecaController = null;
    /**
     * Creates new form PecaUI
     * @param pecaController
     */
    public PecaUI(PecasController pecaController) {
        this.pecaController = pecaController;
        initComponents();
        this.setVisible(true);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.toFront();
        setagemInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBusca = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnEditar = new javax.swing.JButton();
        btnEditar.setEnabled(false);
        btnExcluir = new javax.swing.JButton();
        btnExcluir.setEnabled(false);
        btnCriar = new javax.swing.JButton();
        btnVisualizarPeca = new javax.swing.JButton();
        btnExcluir.setEnabled(false);
        jPanel3 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        campoBusca = new javax.swing.JTextField();
        jRadioButton_Codigo = new javax.swing.JRadioButton();
        jRadioButton_Descricao = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();
        jRadioButton_NomeVariavel = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnRelatorio6 = new javax.swing.JButton();
        btnAtualizarEstoque = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Lista de Produtos");

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Valor", "Quantidade em Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaProdutos.getTableHeader().setReorderingAllowed(false);
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);
        if (tabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutos.getColumnModel().getColumn(0).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelaProdutos.getColumnModel().getColumn(1).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(1).setPreferredWidth(250);
            tabelaProdutos.getColumnModel().getColumn(2).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabelaProdutos.getColumnModel().getColumn(3).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("CONTROLES");

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        btnEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEditarKeyPressed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        btnExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExcluirKeyPressed(evt);
            }
        });

        btnCriar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCriar.setText("CRIAR");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        btnCriar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCriarKeyPressed(evt);
            }
        });

        btnVisualizarPeca.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnVisualizarPeca.setText("VISUALIZAR");
        btnVisualizarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarPecaActionPerformed(evt);
            }
        });
        btnVisualizarPeca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnVisualizarPecaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisualizarPeca, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addGap(102, 102, 102))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCriar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualizarPeca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(242, 242, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("BUSCAR POR");

        campoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaKeyPressed(evt);
            }
        });

        grupoBusca.add(jRadioButton_Codigo);
        jRadioButton_Codigo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton_Codigo.setText("CODIGO");
        jRadioButton_Codigo.setActionCommand("");
        jRadioButton_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_CodigoActionPerformed(evt);
            }
        });

        grupoBusca.add(jRadioButton_Descricao);
        jRadioButton_Descricao.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton_Descricao.setText("DESCRIÇÃO");
        jRadioButton_Descricao.setActionCommand("");
        jRadioButton_Descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_DescricaoActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });

        grupoBusca.add(jRadioButton_NomeVariavel);
        jRadioButton_NomeVariavel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton_NomeVariavel.setText("NOME VARIAVEL");
        jRadioButton_NomeVariavel.setActionCommand("");
        jRadioButton_NomeVariavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_NomeVariavelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton_Descricao)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton_Codigo)
                                .addGap(77, 77, 77)
                                .addComponent(jRadioButton_NomeVariavel)))
                        .addGap(52, 52, 52))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Codigo)
                    .addComponent(jRadioButton_NomeVariavel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_Descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnFechar.setBackground(new java.awt.Color(145, 0, 0));
        btnFechar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("FECHAR");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnRelatorio6.setBackground(new java.awt.Color(0, 153, 153));
        btnRelatorio6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRelatorio6.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorio6.setText("GERAR RELATÓRIO TXT");
        btnRelatorio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorio6ActionPerformed(evt);
            }
        });
        btnRelatorio6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRelatorio6KeyPressed(evt);
            }
        });

        btnAtualizarEstoque.setBackground(new java.awt.Color(0, 204, 0));
        btnAtualizarEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtualizarEstoque.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarEstoque.setText("ATUALIZAR ESTOQUE");
        btnAtualizarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarEstoqueActionPerformed(evt);
            }
        });
        btnAtualizarEstoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAtualizarEstoqueKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRelatorio6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtualizarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtualizarEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRelatorio6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFechar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoR.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(597, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(536, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        produtoAlterar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEditarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            produtoAlterar();
        }
    }//GEN-LAST:event_btnEditarKeyPressed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        produtoExcluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExcluirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            produtoExcluir();
        }
    }//GEN-LAST:event_btnExcluirKeyPressed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        getPecaController().abreCriacaoPeca();
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnCriarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCriarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.setEnabled(false);
            getPecaController().abreCriacaoPeca();
        }
    }//GEN-LAST:event_btnCriarKeyPressed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        getPecaController().fechaPecaUI();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void campoBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            produtoBuscar();
        }
    }//GEN-LAST:event_campoBuscaKeyPressed

    private void jRadioButton_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_CodigoActionPerformed

    private void jRadioButton_DescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_DescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_DescricaoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        produtoBuscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            produtoBuscar();
        }
    }//GEN-LAST:event_btnBuscarKeyPressed

    private void jRadioButton_NomeVariavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NomeVariavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_NomeVariavelActionPerformed

    private void btnVisualizarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarPecaActionPerformed
        produtoVisualizar();
    }//GEN-LAST:event_btnVisualizarPecaActionPerformed

    private void btnVisualizarPecaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVisualizarPecaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            produtoVisualizar();
        }
    }//GEN-LAST:event_btnVisualizarPecaKeyPressed

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        if(tabelaProdutos.getSelectedRow() > -1){
            btnEditar.setEnabled(true);
            btnVisualizarPeca.setEnabled(true);
            btnAtualizarEstoque.setEnabled(true);
            btnExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void btnRelatorio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorio6ActionPerformed
        try {
            geraTxt();
        } catch (IOException ex) {
            Logger.getLogger(PecaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRelatorio6ActionPerformed

    private void btnRelatorio6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRelatorio6KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                geraTxt();
            } catch (IOException ex) {
                Logger.getLogger(PecaUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRelatorio6KeyPressed

    private void btnAtualizarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarEstoqueActionPerformed

    private void btnAtualizarEstoqueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAtualizarEstoqueKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarEstoqueKeyPressed

    private void produtoAlterar(){
        String codigo;
        codigo = (String) tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0);
        Peca pecaAuxLocal;
        String Codigo = null,Descricao = null,PrecoCompra = null,PrecoVenda = null,MargemLucro = null,Marca = null,Modelo = null,Ano = null;
        ArrayList<Especificacao> listaEspecificacoes = new ArrayList();
        ArrayList<String> listaNomesVariantes = new ArrayList();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT * FROM Produto WHERE Codigo = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, codigo);
                ResultSet rs = pst.executeQuery();

                if(rs.next()){
                    Codigo = rs.getString("Codigo");
                    Descricao = rs.getString("Descricao");
                    PrecoCompra = rs.getString("PrecoCompra");
                    PrecoVenda = rs.getString("PrecoVenda");
                    MargemLucro = rs.getString("MargemLucro");
                    Marca = rs.getString("Marca");
                    Modelo = rs.getString("Modelo");
                    Ano = rs.getString("Ano");
                }
            }
        } catch (SQLException | HeadlessException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT * FROM Produto_Variante WHERE CodigoProduto = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, codigo);
                ResultSet rs = pst.executeQuery();
                String nomeVariavel;
                while(rs.next()){
                    nomeVariavel = rs.getString("NomeVariavel");
                    listaNomesVariantes.add(nomeVariavel);
                }
            }
        } catch (SQLException | HeadlessException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT * FROM Produto_Especificacao WHERE CodigoProduto = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, codigo);
                ResultSet rs = pst.executeQuery();
                String descricao, valor, unidadeMedida;
                while(rs.next()){
                    descricao = rs.getString("Descricao");
                    valor = rs.getString("Valor");
                    unidadeMedida = rs.getString("UnidadeMedida");
                    Especificacao esp = new Especificacao(descricao, valor, unidadeMedida);
                    listaEspecificacoes.add(esp);
                }
            }
        } catch (SQLException | HeadlessException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        pecaAuxLocal = new Peca(Codigo,Descricao,PrecoCompra,PrecoVenda,MargemLucro,Marca,Modelo,Ano, listaEspecificacoes, listaNomesVariantes);
        setPecaAux(pecaAuxLocal);
        pecaController.abreEdicaoPeca();
    }
    
    private void produtoVisualizar(){
        String codigo;
        codigo = (String) tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0);
        Peca pecaAuxLocal;
        String Codigo = null,Descricao = null,PrecoCompra = null,PrecoVenda = null,MargemLucro = null,Marca = null,Modelo = null,Ano = null;
        ArrayList<Especificacao> listaEspecificacoes = new ArrayList();
        ArrayList<String> listaNomesVariantes = new ArrayList();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT * FROM Produto WHERE Codigo = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, codigo);
                ResultSet rs = pst.executeQuery();

                if(rs.next()){
                    Codigo = rs.getString("Codigo");
                    Descricao = rs.getString("Descricao");
                    PrecoCompra = rs.getString("PrecoCompra");
                    PrecoVenda = rs.getString("PrecoVenda");
                    MargemLucro = rs.getString("MargemLucro");
                    Marca = rs.getString("Marca");
                    Modelo = rs.getString("Modelo");
                    Ano = rs.getString("Ano");
                }
            }
        } catch (SQLException | HeadlessException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT * FROM Produto_Variante WHERE CodigoProduto = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, codigo);
                ResultSet rs = pst.executeQuery();
                String nomeVariavel;
                while(rs.next()){
                    nomeVariavel = rs.getString("NomeVariavel");
                    listaNomesVariantes.add(nomeVariavel);
                }
            }
        } catch (SQLException | HeadlessException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT * FROM Produto_Especificacao WHERE CodigoProduto = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, codigo);
                ResultSet rs = pst.executeQuery();
                String descricao, valor, unidadeMedida;
                while(rs.next()){
                    descricao = rs.getString("Descricao");
                    valor = rs.getString("Valor");
                    unidadeMedida = rs.getString("UnidadeMedida");
                    Especificacao esp = new Especificacao(descricao, valor, unidadeMedida);
                    listaEspecificacoes.add(esp);
                }
            }
        } catch (SQLException | HeadlessException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        pecaAuxLocal = new Peca(Codigo,Descricao,PrecoCompra,PrecoVenda,MargemLucro,Marca,Modelo,Ano, listaEspecificacoes, listaNomesVariantes);
        setPecaAux(pecaAuxLocal);
        pecaController.abreVisualizacaoPeca();
    }
    
    private void produtoExcluir(){
        int linhaSelecionada = tabelaProdutos.getSelectedRow();
        int colunaSelecionada = 0;
        String message = "Deseja realmente excluir o motorista '" + ((String)tabelaProdutos.getValueAt(linhaSelecionada, 1)) + "'?";
        String title = "Confirmação de Exclusao";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = SQL_URL.getUrl();
                try (Connection con = DriverManager.getConnection(url)) {
                    String sql = "DELETE FROM Produto WHERE Codigo = ?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    colunaSelecionada = 0;
                    pst.setString(1, (String) tabelaProdutos.getValueAt(linhaSelecionada, colunaSelecionada));
                    ResultSet rs = pst.executeQuery();

                }
            } catch (HeadlessException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "O produto '" + (String) tabelaProdutos.getValueAt(linhaSelecionada, 1) + "' foi excluído.");
                setagemInicial();
                produtoBuscaTodos();
            }
        }
        if (reply == JOptionPane.NO_OPTION) {

        }
    }
    
    private void produtoBuscar(){
        if (jRadioButton_Codigo.isSelected() || jRadioButton_Descricao.isSelected()){
            limpaTabelaProdutos();
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = SQL_URL.getUrl();
                try (Connection con = DriverManager.getConnection(url)) {
                    String sql = null;
                    String palavraBusca = campoBusca.getText();
                    if (palavraBusca.equals("")) {
                        produtoBuscaTodos();
                    } else {
                        if (jRadioButton_Codigo.isSelected()) {
                            sql = "SELECT Codigo, Descricao, PrecoVenda, QtdEstoque FROM Produto WHERE Codigo LIKE '%"+palavraBusca+"%'";
                        } else if (jRadioButton_Descricao.isSelected()) {
                            sql = "SELECT Codigo, Descricao, PrecoVenda, QtdEstoque FROM Produto WHERE Descricao LIKE '%"+palavraBusca+"%'";
                        }
                        PreparedStatement pst = con.prepareStatement(sql);;
                        ResultSet rs = pst.executeQuery();
                        while (rs.next()) {
                            DefaultTableModel modeloAux = (DefaultTableModel) tabelaProdutos.getModel();
                            modeloAux.addRow(new Object[]{rs.getString("Codigo"), rs.getString("Descricao"), rs.getString("PrecoVenda"), rs.getString("QtdEstoque")});
                        }
                    }
                    
                    if (tabelaProdutos.getRowCount() == 0) {
                        JOptionPane.showMessageDialog(null, "A pesquisa não encontrou nenhum produto.");
                    }
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else if(jRadioButton_NomeVariavel.isSelected()){
            String palavraBusca = campoBusca.getText();
            buscaNomeVariavel(palavraBusca);
        }else {
            JOptionPane.showMessageDialog(null, "Selecione um filtro de busca.");
        }
    }
    
    private void buscaNomeVariavel(String palavraBusca){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql;
                sql = "SELECT CodigoProduto FROM Produto_Variante WHERE Nome_Variavel LIKE '%"+palavraBusca+"%'";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    buscaNomeVariavelContinue(rs.getString("CodigoProduto"));
                }
                if (tabelaProdutos.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "A pesquisa não encontrou nenhum produto.");
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            //JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void buscaNomeVariavelContinue(String codigo){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = null;
                sql = "SELECT Codigo, Descricao, PrecoVenda, QtdEstoque FROM Produto WHERE Codigo = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, codigo);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    DefaultTableModel modeloAux = (DefaultTableModel) tabelaProdutos.getModel();
                    modeloAux.addRow(new Object[]{rs.getString("Codigo"), rs.getString("Descricao"), rs.getString("PrecoVenda"), rs.getString("QtdEstoque")});
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            //JOptionPane.showMessageDialog(null, e);
        }
    }
    public void produtoBuscaTodos(){
        limpaTabelaProdutos();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = null;
                sql = "SELECT * FROM Produto";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    DefaultTableModel modeloAux = (DefaultTableModel) tabelaProdutos.getModel();
                    modeloAux.addRow(new Object[]{rs.getString("Codigo"), rs.getString("Descricao"), rs.getString("PrecoVenda"), rs.getString("QtdEstoque")});
                }
                if (tabelaProdutos.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "A pesquisa não encontrou nenhum produto.");
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public final void setagemInicial(){
        btnEditar.setEnabled(false);
        btnVisualizarPeca.setEnabled(false);
        btnAtualizarEstoque.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
    private void limpaTabelaProdutos(){
        int rowCount = tabelaProdutos.getRowCount();
        if (rowCount > 0) {
            while (rowCount > 0) {
                ((DefaultTableModel) tabelaProdutos.getModel()).removeRow(rowCount - 1);
                rowCount--;
            }
        }
    }
    
    private void geraTxt() throws IOException{
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
	Date date = new Date();
	String dataAux = dateFormat.format(date);
        dataAux = dataAux.replaceAll(" ", "--");
        dataAux = dataAux.replaceAll("/", "-");
        dataAux = dataAux.replaceAll(":", "");
        
        File f = new File(".\\saida");
        if(f.mkdir()){
        }
        f = new File(".\\saida\\produtos");
        if(f.mkdir()){
        }
        
        try (FileWriter arq = new FileWriter(".\\saida\\produtos/BuscaProdutos--"+dataAux+".txt")) {
            PrintWriter gravarArq = new PrintWriter(arq);

            gravarArq.printf("+-------------- RESULTADO DA BUSCA: PRODUTOS --------------+%n%n");
            gravarArq.printf("LISTAGEM:%n%n");
            int i;
            for (i=0; i< tabelaProdutos.getRowCount(); i++) {
                gravarArq.printf("# %2d ##########################%n", i+1);
                gravarArq.printf("Código: " + (String)tabelaProdutos.getValueAt(i, 0)+"%n");
                gravarArq.printf("Descrição: " + (String)tabelaProdutos.getValueAt(i, 1)+"%n");
                gravarArq.printf("Valor: " + (String)tabelaProdutos.getValueAt(i, 2)+"%n");
                gravarArq.printf("Quantidade em Estoque: " + (String)tabelaProdutos.getValueAt(i, 3)+"%n");
                ArrayList objetos[] = searchPeca((String)tabelaProdutos.getValueAt(i, 0));
                ArrayList auxList = objetos[0];
                Iterator auxIterador = auxList.iterator();
                int num = 1;
                Especificacao espAux;
                while (auxIterador.hasNext()){
                    espAux = (Especificacao)auxIterador.next();
                    gravarArq.printf("-Especificacao "+ num +"-" +"%n");
                    gravarArq.printf("Descrição: "+ espAux.getDescricao() +"%n");
                    gravarArq.printf("Unidade de Medida: "+ espAux.getUnidadeMedida() +"%n");
                    gravarArq.printf("Valor: "+ espAux.getValor() +"%n");
                    gravarArq.printf("-------------------%n");
                    num++;
                }
                auxList = objetos[1];
                auxIterador = auxList.iterator();
                num = 1;
                String stringAux;
                while (auxIterador.hasNext()){
                    stringAux = (String)auxIterador.next();
                    gravarArq.printf("Nome Variante "+ num +": " + stringAux + "%n");
                    num++;
                }
                gravarArq.printf("%n");
            }
            gravarArq.printf("+-------------------------------------------------------------+%n");
            arq.close();

            JOptionPane.showMessageDialog(null,"Dados salvos em 'saida/produtos/BuscaProdutos--"+dataAux+".txt'");
        }
    }
    
    private ArrayList[] searchPeca(String codigo){
        ArrayList[] objetos = new ArrayList[2];
        ArrayList<Especificacao> listaEspecificacoes = new ArrayList();
        ArrayList<String> listaNomesVariantes = new ArrayList();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = null;
                sql = "SELECT * FROM Produto_Especificacao WHERE CodigoProduto = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, codigo);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    Especificacao auxEsp = new Especificacao(rs.getString("Descricao"),rs.getString("Valor"),rs.getString("UnidadeMedida"));
                    listaEspecificacoes.add(auxEsp);
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            //JOptionPane.showMessageDialog(null, e);
        }
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = null;
                sql = "SELECT * FROM Produto_Variante WHERE CodigoProduto = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, codigo);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String auxString = rs.getString("NomeVariavel");
                    listaNomesVariantes.add(auxString);
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            //JOptionPane.showMessageDialog(null, e);
        }
        
        objetos[0] = listaEspecificacoes;
        objetos[1] = listaNomesVariantes;
        
        return objetos;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PecaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarEstoque;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRelatorio6;
    private javax.swing.JButton btnVisualizarPeca;
    private javax.swing.JTextField campoBusca;
    private javax.swing.ButtonGroup grupoBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton_Codigo;
    private javax.swing.JRadioButton jRadioButton_Descricao;
    private javax.swing.JRadioButton jRadioButton_NomeVariavel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the editarPeca
     */
    public EditarPeca getEditarPeca() {
        return editarPeca;
    }

    /**
     * @param editarPeca the editarPeca to set
     */
    public void setEditarPeca(EditarPeca editarPeca) {
        this.editarPeca = editarPeca;
    }

    /**
     * @return the pecaController
     */
    public PecasController getPecaController() {
        return pecaController;
    }

    /**
     * @param pecaController the pecaController to set
     */
    public void setPecaController(PecasController pecaController) {
        this.pecaController = pecaController;
    }

    /**
     * @return the pecaAux
     */
    public Peca getPecaAux() {
        return pecaAux;
    }

    /**
     * @param pecaAux the pecaAux to set
     */
    public void setPecaAux(Peca pecaAux) {
        this.pecaAux = pecaAux;
    }

    /**
     * @return the criarPeca
     */
    public CriarPeca getCriarPeca() {
        return criarPeca;
    }

    /**
     * @param criarPeca the criarPeca to set
     */
    public void setCriarPeca(CriarPeca criarPeca) {
        this.criarPeca = criarPeca;
    }

    /**
     * @return the visualizarPeca
     */
    public VisualizarPeca getVisualizarPeca() {
        return visualizarPeca;
    }

    /**
     * @param visualizarPeca the visualizarPeca to set
     */
    public void setVisualizarPeca(VisualizarPeca visualizarPeca) {
        this.visualizarPeca = visualizarPeca;
    }
}
