/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.emprestimo;

import controller.EmprestimoController;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Emprestimo;
import util.SQL_URL;

/**
 *
 * @author KLEYN
 */
public class EmprestimoUI extends javax.swing.JFrame {

    private Emprestimo emprestimoAux = null;
    private CriarEmprestimo criarEmprestimo= null;
    private EditarEmprestimo editarEmprestimo = null;
    
    private EmprestimoController emprestimoController = null;
    /**
     * Creates new form EmprestimoUI
     * @param emprestimoController
     */
    public EmprestimoUI(EmprestimoController emprestimoController) {
        this.emprestimoController = emprestimoController;
        initComponents();
        this.setVisible(true);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.toFront();
        setagemInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEmprestimos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnEditar = new javax.swing.JButton();
        btnEditar.setEnabled(false);
        btnExcluir = new javax.swing.JButton();
        btnExcluir.setEnabled(false);
        btnCriar = new javax.swing.JButton();
        btnDevolucao = new javax.swing.JButton();
        btnExcluir.setEnabled(false);
        jPanel3 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        campoBusca = new javax.swing.JTextField();
        jRadioButton_Item = new javax.swing.JRadioButton();
        jRadioButton_Funcionario = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();
        jRadioButton_Setor = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Lista de Empréstimos");

        tabelaEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "ITEM", "FUNCIONÁRIO", "QUANTIDADE", "SETOR", "DIA DE EMPRESTIMO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEmprestimos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaEmprestimos.getTableHeader().setReorderingAllowed(false);
        tabelaEmprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEmprestimosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaEmprestimos);
        if (tabelaEmprestimos.getColumnModel().getColumnCount() > 0) {
            tabelaEmprestimos.getColumnModel().getColumn(0).setResizable(false);
            tabelaEmprestimos.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelaEmprestimos.getColumnModel().getColumn(1).setResizable(false);
            tabelaEmprestimos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabelaEmprestimos.getColumnModel().getColumn(2).setResizable(false);
            tabelaEmprestimos.getColumnModel().getColumn(2).setPreferredWidth(200);
            tabelaEmprestimos.getColumnModel().getColumn(3).setResizable(false);
            tabelaEmprestimos.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabelaEmprestimos.getColumnModel().getColumn(4).setResizable(false);
            tabelaEmprestimos.getColumnModel().getColumn(4).setPreferredWidth(150);
            tabelaEmprestimos.getColumnModel().getColumn(5).setResizable(false);
            tabelaEmprestimos.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoR.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("CONTROLES");

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        btnEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEditarKeyPressed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        btnExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExcluirKeyPressed(evt);
            }
        });

        btnCriar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCriar.setText("LANÇAMENTO");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        btnCriar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCriarKeyPressed(evt);
            }
        });

        btnDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnDevolucao.setText("DEVOLUÇÃO");
        btnDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucaoActionPerformed(evt);
            }
        });
        btnDevolucao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDevolucaoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCriar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDevolucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(242, 242, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("BUSCAR POR");

        campoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaKeyPressed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Item);
        jRadioButton_Item.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton_Item.setText("ITEM");
        jRadioButton_Item.setActionCommand("");
        jRadioButton_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ItemActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Funcionario);
        jRadioButton_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton_Funcionario.setText("FUNCIONARIO");
        jRadioButton_Funcionario.setActionCommand("");
        jRadioButton_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FuncionarioActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Setor);
        jRadioButton_Setor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton_Setor.setText("SETOR");
        jRadioButton_Setor.setActionCommand("");
        jRadioButton_Setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_SetorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton_Funcionario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoBusca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton_Item)
                                .addGap(72, 72, 72)
                                .addComponent(jRadioButton_Setor)
                                .addGap(87, 87, 87)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Item)
                    .addComponent(jRadioButton_Setor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_Funcionario)
                .addGap(31, 31, 31)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFechar.setBackground(new java.awt.Color(145, 0, 0));
        btnFechar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("FECHAR");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnRelatorio.setBackground(new java.awt.Color(0, 153, 153));
        btnRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setText("GERAR RELATÓRIO TXT");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1056, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaEmprestimosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEmprestimosMouseClicked
        if(tabelaEmprestimos.getSelectedRow() > -1){
            btnEditar.setEnabled(true);
            btnDevolucao.setEnabled(true);
            btnExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaEmprestimosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        emprestimoAlterar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEditarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            emprestimoAlterar();
        }
    }//GEN-LAST:event_btnEditarKeyPressed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        emprestimoExcluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExcluirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            emprestimoExcluir();
        }
    }//GEN-LAST:event_btnExcluirKeyPressed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        getEmprestimoController().abreCriacaoEmprestimo();
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnCriarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCriarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.setEnabled(false);
            getEmprestimoController().abreCriacaoEmprestimo();
        }
    }//GEN-LAST:event_btnCriarKeyPressed

    private void btnDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucaoActionPerformed
        emprestimoDevolver();
    }//GEN-LAST:event_btnDevolucaoActionPerformed

    private void btnDevolucaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDevolucaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            emprestimoDevolver();
        }
    }//GEN-LAST:event_btnDevolucaoKeyPressed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        getEmprestimoController().fechaEmprestimoUI();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void campoBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            emprestimoBuscar();
        }
    }//GEN-LAST:event_campoBuscaKeyPressed

    private void jRadioButton_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_ItemActionPerformed

    private void jRadioButton_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_FuncionarioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        emprestimoBuscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            emprestimoBuscar();
        }
    }//GEN-LAST:event_btnBuscarKeyPressed

    private void jRadioButton_SetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_SetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_SetorActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        try {
            geraTxt();
        } catch (IOException ex) {
            Logger.getLogger(EmprestimoUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRelatorioActionPerformed

    
    public void setagemInicial(){
        btnEditar.setEnabled(false);
        btnDevolucao.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
    private void emprestimoAlterar(){
        if(tabelaEmprestimos.getSelectedRow() > -1){
            try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT * FROM Emprestimo WHERE Codigo = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, (String)tabelaEmprestimos.getValueAt(tabelaEmprestimos.getSelectedRow(), 0));
                ResultSet rs = pst.executeQuery();

                if(rs.next()){
                    emprestimoAux = new Emprestimo(rs.getString("Item"),rs.getString("Funcionario"),rs.getString("Quantidade"),rs.getString("Setor"),rs.getString("Codigo"),rs.getString("DiadeEmprestimo"));
                    setEmprestimoAux(emprestimoAux);
                    emprestimoController.abreEdicaoEmprestimo();
                }
            }
            } catch (SQLException | HeadlessException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    
    
    private void emprestimoDevolver(){
        if(tabelaEmprestimos.getSelectedRow() > -1){
            String message = "Deseja realmente confirmar a devolução?";
            String title = "Confirmar Devolução";
            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                confirmaDevolucao();
            }
            if (reply == JOptionPane.NO_OPTION) {

            }
        }
    }
    
    private void confirmaDevolucao(){
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
	Date date = new Date();
	String dataAux = dateFormat.format(date);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "UPDATE Emprestimo SET Devolvido = ?, DiaDeDevolucao = ? WHERE Codigo = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, "S");
                pst.setString(2, dataAux);
                pst.setString(3, (String)tabelaEmprestimos.getValueAt(tabelaEmprestimos.getSelectedRow(), 0));
                ResultSet rs = pst.executeQuery();

                if(rs.next()){
                    // FAZ NADA
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Item '" + (String)tabelaEmprestimos.getValueAt(tabelaEmprestimos.getSelectedRow(), 1) + "' devolvido com sucesso.");
            //JOptionPane.showMessageDialog(null,e);
            emprestimoBuscaTodos();
        } catch (HeadlessException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void emprestimoExcluir(){
        int linhaSelecionada = tabelaEmprestimos.getSelectedRow();
        int colunaSelecionada = 1;
        String message = "Deseja realmente excluir o empréstimo '" + ((String)tabelaEmprestimos.getValueAt(linhaSelecionada, colunaSelecionada)) + "'?";
        String title = "Confirmação de Exclusao";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = SQL_URL.getUrl();
                try (Connection con = DriverManager.getConnection(url)) {
                    String sql = "DELETE FROM Emprestimo WHERE Codigo = ?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    colunaSelecionada = 0;
                    pst.setString(1, (String) tabelaEmprestimos.getValueAt(linhaSelecionada, colunaSelecionada));
                    ResultSet rs = pst.executeQuery();

                }
            } catch (HeadlessException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
            } catch (SQLException e) {
                colunaSelecionada = 1;
                JOptionPane.showMessageDialog(null, "O motorista '" + (String) tabelaEmprestimos.getValueAt(linhaSelecionada, colunaSelecionada) + "' foi excluído.");
                setagemInicial();
                emprestimoBuscaTodos();
            }
            if (reply == JOptionPane.NO_OPTION) {

            }
        }
    }
    
    public void emprestimoBuscaTodos(){
        limpaTabelaEmprestimos();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = null;
                sql = "SELECT * FROM Emprestimo WHERE Devolvido = 'N'";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    DefaultTableModel modeloAux = (DefaultTableModel) tabelaEmprestimos.getModel();
                    modeloAux.addRow(new Object[]{rs.getString("Codigo"), rs.getString("Item"), rs.getString("Funcionario"), rs.getString("Quantidade"), rs.getString("Setor"), rs.getString("DiaDeEmprestimo")});
                }
                if (tabelaEmprestimos.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "A pesquisa não encontrou nenhuma devolução.");
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            //JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void limpaTabelaEmprestimos(){
        int rowCount = tabelaEmprestimos.getRowCount();
        if (rowCount > 0) {
            while (rowCount > 0) {
                ((DefaultTableModel) tabelaEmprestimos.getModel()).removeRow(rowCount - 1);
                rowCount--;
            }
        }
    }
    
    private void emprestimoBuscar(){
        if (jRadioButton_Item.isSelected() || jRadioButton_Funcionario.isSelected() || jRadioButton_Setor.isSelected()){
            limpaTabelaEmprestimos();
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = SQL_URL.getUrl();
                try (Connection con = DriverManager.getConnection(url)) {
                    String sql = null;
                    String palavraBusca = campoBusca.getText();
                    if (palavraBusca.equals("")) {
                        emprestimoBuscaTodos();
                    } else {
                        if (jRadioButton_Item.isSelected()) {
                            sql = "SELECT * FROM Emprestimo WHERE Devolvido = 'N' AND Item LIKE '%"+palavraBusca+"%'";
                        } else if (jRadioButton_Funcionario.isSelected()) {
                            sql = "SELECT * FROM Emprestimo WHERE Devolvido = 'N' AND Funcionario LIKE '%"+palavraBusca+"%'";
                        } else if (jRadioButton_Setor.isSelected()) {
                            sql = "SELECT * FROM Emprestimo WHERE Devolvido = 'N' AND Setor LIKE '%"+palavraBusca+"%'";
                        }
                        
                        PreparedStatement pst = con.prepareStatement(sql);
                        //pst.setString(1, palavraBusca);
                        ResultSet rs = pst.executeQuery();
                        while (rs.next()) {
                            DefaultTableModel modeloAux = (DefaultTableModel) tabelaEmprestimos.getModel();
                            modeloAux.addRow(new Object[]{rs.getString("Codigo"), rs.getString("Item"), rs.getString("Funcionario"), rs.getString("Quantidade"), rs.getString("Setor"), rs.getString("DiaDeEmprestimo")});
                        }
                        if (tabelaEmprestimos.getRowCount() == 0) {
                            JOptionPane.showMessageDialog(null, "A pesquisa não encontrou nenhum empréstimo.");
                        }
                    }
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            //ajustaTabela(tabelaMotoristas);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um filtro de busca.");
        }
    }
    
    private void geraTxt() throws IOException{
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
	Date date = new Date();
	String dataAux = dateFormat.format(date);
        dataAux = dataAux.replaceAll(" ", "--");
        dataAux = dataAux.replaceAll("/", "-");
        dataAux = dataAux.replaceAll(":", "");
        
        File f = new File(".\\saida");
        if(f.mkdir()){
        }
        f = new File(".\\saida\\emprestimo");
        if(f.mkdir()){
        }
        
        try (FileWriter arq = new FileWriter(".\\saida\\emprestimo/BuscaEmprestimo--"+dataAux+".txt")) {
            PrintWriter gravarArq = new PrintWriter(arq);

            gravarArq.printf("+-------------- RESULTADO DA BUSCA: EMPRÉSTIMOS --------------+%n%n");
            gravarArq.printf("LISTAGEM:%n%n");
            int i;
            for (i=0; i< tabelaEmprestimos.getRowCount(); i++) {
                gravarArq.printf("# %2d ##########%n", i+1);
                gravarArq.printf("Código: " + (String)tabelaEmprestimos.getValueAt(i, 0)+"%n");
                gravarArq.printf("Item: " + (String)tabelaEmprestimos.getValueAt(i, 1)+"%n");
                gravarArq.printf("Funcionário: " + (String)tabelaEmprestimos.getValueAt(i, 2)+"%n");
                gravarArq.printf("Quantidade: " + (String)tabelaEmprestimos.getValueAt(i, 3)+"%n");
                gravarArq.printf("Setor: " + (String)tabelaEmprestimos.getValueAt(i, 4)+"%n");
                gravarArq.printf("Dia de Empréstimo: " + (String)tabelaEmprestimos.getValueAt(i, 5)+"%n%n%n");
            }
            gravarArq.printf("+-------------------------------------------------------------+%n");
            arq.close();

            JOptionPane.showMessageDialog(null,"Dados salvos em 'saida/emprestimo/BuscaEmprestimo--"+dataAux+".txt'");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmprestimoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnDevolucao;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton_Funcionario;
    private javax.swing.JRadioButton jRadioButton_Item;
    private javax.swing.JRadioButton jRadioButton_Setor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable tabelaEmprestimos;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the emprestimoAux
     */
    public Emprestimo getEmprestimoAux() {
        return emprestimoAux;
    }

    /**
     * @param emprestimoAux the emprestimoAux to set
     */
    public void setEmprestimoAux(Emprestimo emprestimoAux) {
        this.emprestimoAux = emprestimoAux;
    }

    /**
     * @return the criarEmprestimo
     */
    public CriarEmprestimo getCriarEmprestimo() {
        return criarEmprestimo;
    }

    /**
     * @param criarEmprestimo the criarEmprestimo to set
     */
    public void setCriarEmprestimo(CriarEmprestimo criarEmprestimo) {
        this.criarEmprestimo = criarEmprestimo;
    }

    /**
     * @return the editarEmprestimo
     */
    public EditarEmprestimo getEditarEmprestimo() {
        return editarEmprestimo;
    }

    /**
     * @param editarEmprestimo the editarEmprestimo to set
     */
    public void setEditarEmprestimo(EditarEmprestimo editarEmprestimo) {
        this.editarEmprestimo = editarEmprestimo;
    }

    /**
     * @return the emprestimoController
     */
    public EmprestimoController getEmprestimoController() {
        return emprestimoController;
    }

    /**
     * @param emprestimoController the emprestimoController to set
     */
    public void setEmprestimoController(EmprestimoController emprestimoController) {
        this.emprestimoController = emprestimoController;
    }
}
