/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.veiculo;

import controller.VeiculoController;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Veiculo;
import util.SQL_URL;

/**
 *
 * @author KLEYN
 */
public class VeiculoUI extends javax.swing.JFrame {
    
    private Veiculo veiculoAux = null;
    private CriarVeiculo criarVeiculo = null;
    private EditarVeiculo editarVeiculo = null;
    private VisualizarVeiculo visualizarVeiculo = null;

    private VeiculoController veiculoController = null;
    
    /**
     * Creates new form VeiculoUI
     * @param veiculoController
     */
    public VeiculoUI(VeiculoController veiculoController) {
        this.veiculoController = veiculoController;
        initComponents();
        this.setVisible(true);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.toFront();
        setagemInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVeiculos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnEditar = new javax.swing.JButton();
        btnEditar.setEnabled(false);
        btnExcluir = new javax.swing.JButton();
        btnExcluir.setEnabled(false);
        btnCriar = new javax.swing.JButton();
        btnVisualizacao = new javax.swing.JButton();
        btnExcluir.setEnabled(false);
        jPanel3 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        campoBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        radio_Placa = new javax.swing.JRadioButton();
        radio_Modelo = new javax.swing.JRadioButton();
        radio_Marca = new javax.swing.JRadioButton();
        radio_Renavam = new javax.swing.JRadioButton();
        radio_Chassi = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("LISTA DE VEÍCULOS");

        tabelaVeiculos.setBackground(new java.awt.Color(250, 250, 250));
        tabelaVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "PLACA", "MARCA", "MODELO", "RENAVAM", "Nº CHASSI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaVeiculos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaVeiculos.getTableHeader().setReorderingAllowed(false);
        tabelaVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVeiculos);
        if (tabelaVeiculos.getColumnModel().getColumnCount() > 0) {
            tabelaVeiculos.getColumnModel().getColumn(0).setResizable(false);
            tabelaVeiculos.getColumnModel().getColumn(1).setResizable(false);
            tabelaVeiculos.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabelaVeiculos.getColumnModel().getColumn(2).setResizable(false);
            tabelaVeiculos.getColumnModel().getColumn(2).setPreferredWidth(150);
            tabelaVeiculos.getColumnModel().getColumn(3).setResizable(false);
            tabelaVeiculos.getColumnModel().getColumn(3).setPreferredWidth(150);
            tabelaVeiculos.getColumnModel().getColumn(4).setResizable(false);
            tabelaVeiculos.getColumnModel().getColumn(4).setPreferredWidth(150);
            tabelaVeiculos.getColumnModel().getColumn(5).setResizable(false);
            tabelaVeiculos.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoR.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("CONTROLES");

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        btnEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEditarKeyPressed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        btnExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExcluirKeyPressed(evt);
            }
        });

        btnCriar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCriar.setText("LANÇAMENTO");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        btnCriar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCriarKeyPressed(evt);
            }
        });

        btnVisualizacao.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnVisualizacao.setText("VISUALIZAÇÃO");
        btnVisualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizacaoActionPerformed(evt);
            }
        });
        btnVisualizacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnVisualizacaoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVisualizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCriar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addGap(29, 29, 29))
        );

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("BUSCAR POR");

        campoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaKeyPressed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });

        radio_Placa.setBackground(new java.awt.Color(250, 250, 250));
        buttonGroup1.add(radio_Placa);
        radio_Placa.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        radio_Placa.setText("PLACA");
        radio_Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_PlacaActionPerformed(evt);
            }
        });

        radio_Modelo.setBackground(new java.awt.Color(250, 250, 250));
        buttonGroup1.add(radio_Modelo);
        radio_Modelo.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        radio_Modelo.setText("MODELO");

        radio_Marca.setBackground(new java.awt.Color(250, 250, 250));
        buttonGroup1.add(radio_Marca);
        radio_Marca.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        radio_Marca.setText("MARCA");

        radio_Renavam.setBackground(new java.awt.Color(250, 250, 250));
        buttonGroup1.add(radio_Renavam);
        radio_Renavam.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        radio_Renavam.setText("RENAVAM");

        radio_Chassi.setBackground(new java.awt.Color(250, 250, 250));
        buttonGroup1.add(radio_Chassi);
        radio_Chassi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        radio_Chassi.setText("Nº CHASSI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_Marca)
                            .addComponent(radio_Placa))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(radio_Renavam)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(radio_Modelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radio_Chassi))))
                    .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_Placa)
                    .addComponent(radio_Modelo)
                    .addComponent(radio_Chassi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_Marca)
                    .addComponent(radio_Renavam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(20, 20, 20))
        );

        btnFechar.setBackground(new java.awt.Color(145, 0, 0));
        btnFechar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("FECHAR");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnRelatorio.setBackground(new java.awt.Color(0, 153, 153));
        btnRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setText("GERAR RELATÓRIO TXT");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVeiculosMouseClicked
        if(tabelaVeiculos.getSelectedRow() > -1){
            btnEditar.setEnabled(true);
            btnVisualizacao.setEnabled(true);
            btnExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaVeiculosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        veiculoAlterar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEditarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            veiculoAlterar();
        }
    }//GEN-LAST:event_btnEditarKeyPressed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        veiculoExcluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExcluirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            veiculoExcluir();
        }
    }//GEN-LAST:event_btnExcluirKeyPressed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        getVeiculoController().abreCriacaoVeiculo();
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnCriarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCriarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getVeiculoController().abreCriacaoVeiculo();
        }
    }//GEN-LAST:event_btnCriarKeyPressed

    private void btnVisualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizacaoActionPerformed
        veiculoVisualizacao();
    }//GEN-LAST:event_btnVisualizacaoActionPerformed

    private void btnVisualizacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVisualizacaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            veiculoVisualizacao();
        }
    }//GEN-LAST:event_btnVisualizacaoKeyPressed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        getVeiculoController().fechaVeiculoUI();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        try {
            geraTxt();
        } catch (IOException ex) {
            Logger.getLogger(VeiculoUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void radio_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_PlacaActionPerformed

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            veiculoBuscar();
        }
    }//GEN-LAST:event_btnBuscarKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        veiculoBuscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void campoBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            veiculoBuscar();
        }
    }//GEN-LAST:event_campoBuscaKeyPressed

    public final void setagemInicial(){
        btnEditar.setEnabled(false);
        btnVisualizacao.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
    private void geraTxt() throws IOException{
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
	Date date = new Date();
	String dataAux = dateFormat.format(date);
        dataAux = dataAux.replaceAll(" ", "--");
        dataAux = dataAux.replaceAll("/", "-");
        dataAux = dataAux.replaceAll(":", "");
        
        File f = new File(".\\saida");
        if(f.mkdir()){
        }
        f = new File(".\\saida\\veiculos");
        if(f.mkdir()){
        }
        
        try (FileWriter arq = new FileWriter(".\\saida\\veiculos/BuscaVeiculos--"+dataAux+".txt")) {
            PrintWriter gravarArq = new PrintWriter(arq);

            gravarArq.printf("+-------------- RESULTADO DA BUSCA: VEÍCULOS --------------+%n%n");
            gravarArq.printf("LISTAGEM:%n%n");
            int i;
            for (i=0; i< tabelaVeiculos.getRowCount(); i++) {
                gravarArq.printf("# %2d ##########################%n", i+1);
                gravarArq.printf("Placa: " + (String)tabelaVeiculos.getValueAt(i, 1)+"%n");
                gravarArq.printf("Marca: " + (String)tabelaVeiculos.getValueAt(i, 2)+"%n");
                gravarArq.printf("Modelo: " + (String)tabelaVeiculos.getValueAt(i, 3)+"%n");
                gravarArq.printf("Renavam: " + (String)tabelaVeiculos.getValueAt(i, 4)+"%n");
                gravarArq.printf("Chassi: " + (String)tabelaVeiculos.getValueAt(i, 5)+"%n");
                gravarArq.printf("%n");
            }
            gravarArq.printf("+-------------------------------------------------------------+%n");
            arq.close();

            JOptionPane.showMessageDialog(null,"Dados salvos em 'saida/veiculos/BuscaVeiculos--"+dataAux+".txt'");
        }
    }
    
    private void veiculoAlterar(){
        String placa;
        placa = (String) tabelaVeiculos.getValueAt(tabelaVeiculos.getSelectedRow(), 1);
        Veiculo veiculoAux2;
        String Placa, Modelo, Marca, Pais, Ano, Renavam, Eixos, NChassi, NMotor, Cor;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT * FROM Veiculo WHERE Placa = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, placa);
                ResultSet rs = pst.executeQuery();

                if(rs.next()){
                    Placa = rs.getString("Placa");
                    Modelo = rs.getString("Modelo");
                    Marca = rs.getString("Marca");
                    Pais = rs.getString("Pais");
                    Ano = rs.getString("Ano");
                    Renavam = rs.getString("Renavam");
                    Eixos = rs.getString("NumeroEixos");
                    NChassi = rs.getString("NumeroChassi");
                    NMotor = rs.getString("NroMotor");
                    Cor = rs.getString("Cor");
                    
                    ArrayList<String> listaCaracteristicas = buscaCaracteristicas(Placa);
                    
                    veiculoAux2 = new Veiculo(Placa, Marca, Modelo, Pais, Renavam, Ano, Eixos, NChassi, NMotor, Cor, listaCaracteristicas);
                    setVeiculoAux(veiculoAux2);
                    veiculoController.abreEdicaoVeiculo();
                }
            }
        } catch (SQLException | HeadlessException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private ArrayList<String> buscaCaracteristicas(String Placa){
        ArrayList<String> listaCaracteristicas = new ArrayList();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VeiculoUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        String url = SQL_URL.getUrl();
        try (Connection con = DriverManager.getConnection(url)) {
            String sql = "SELECT Caracteristica FROM Veiculo_Caracteristica WHERE PlacaVeiculo = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, Placa);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                listaCaracteristicas.add(rs.getString("Caracteristica"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(VeiculoUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return listaCaracteristicas;
    }
    
    private void veiculoExcluir(){
        int linhaSelecionada = tabelaVeiculos.getSelectedRow();
        int colunaSelecionada = 1;
        String message = "Deseja realmente excluir o veículo de placa '" + ((String)tabelaVeiculos.getValueAt(linhaSelecionada, colunaSelecionada)) + "'?";
        String title = "Confirmação de Exclusao";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = SQL_URL.getUrl();
                try (Connection con = DriverManager.getConnection(url)) {
                    String sql = "DELETE FROM Veiculo WHERE Placa = ?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, (String) tabelaVeiculos.getValueAt(linhaSelecionada, colunaSelecionada));
                    pst.execute();
                    con.close();
                    deletaCaracteristica((String) tabelaVeiculos.getValueAt(linhaSelecionada, colunaSelecionada));
                    
                    JOptionPane.showMessageDialog(null, "O veículo de placa '" + (String) tabelaVeiculos.getValueAt(linhaSelecionada, colunaSelecionada) + "' foi excluído.");
                    setagemInicial();
                    veiculoBuscaTodos();
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (reply == JOptionPane.NO_OPTION) {

        }
    }
    
    private void deletaCaracteristica(String placa){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "DELETE FROM Veiculo_Caracteristica WHERE PlacaVeiculo = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, placa);
                pst.execute();
                con.close();
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void veiculoVisualizacao(){
        String placa;
        placa = (String) tabelaVeiculos.getValueAt(tabelaVeiculos.getSelectedRow(), 1);
        Veiculo veiculoAux2;
        String Placa, Modelo, Marca, Pais, Ano, Renavam, Eixos, NChassi, NMotor, Cor;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT * FROM Veiculo WHERE Placa = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, placa);
                ResultSet rs = pst.executeQuery();

                if(rs.next()){
                    Placa = rs.getString("Placa");
                    Modelo = rs.getString("Modelo");
                    Marca = rs.getString("Marca");
                    Pais = rs.getString("Pais");
                    Ano = rs.getString("Ano");
                    Renavam = rs.getString("Renavam");
                    Eixos = rs.getString("NumeroEixos");
                    NChassi = rs.getString("NumeroChassi");
                    NMotor = rs.getString("NroMotor");
                    Cor = rs.getString("Cor");
                    
                    ArrayList<String> listaCaracteristicas = buscaCaracteristicas(Placa);
                    
                    veiculoAux2 = new Veiculo(Placa, Marca, Modelo, Pais, Renavam, Ano, Eixos, NChassi, NMotor, Cor, listaCaracteristicas);
                    setVeiculoAux(veiculoAux2);
                    veiculoController.abreVisualizacaoVeiculo();
                }
            }
        } catch (SQLException | HeadlessException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void veiculoBuscar(){
        if (radio_Placa.isSelected() || radio_Marca.isSelected() || radio_Modelo.isSelected() || radio_Renavam.isSelected() || radio_Chassi.isSelected()){
            limpaTabelaVeiculos();
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = SQL_URL.getUrl();
                try (Connection con = DriverManager.getConnection(url)) {
                    String sql = null;
                    String palavraBusca = campoBusca.getText();
                    if (palavraBusca.equals("")) {
                        veiculoBuscaTodos();
                    } else {
                        if (radio_Placa.isSelected()) {
                            sql = "SELECT Placa, Marca, Modelo, Renavam, NumeroChassi FROM Veiculo WHERE Placa LIKE '%"+palavraBusca+"%'";
                        } else if (radio_Marca.isSelected()) {
                            sql = "SELECT Placa, Marca, Modelo, Renavam, NumeroChassi FROM Veiculo WHERE Marca LIKE '%"+palavraBusca+"%'";
                        } else if (radio_Modelo.isSelected()){
                            sql = "SELECT Placa, Marca, Modelo, Renavam, NumeroChassi FROM Veiculo WHERE Modelo LIKE '%"+palavraBusca+"%'";
                        } else if (radio_Renavam.isSelected()){
                            sql = "SELECT Placa, Marca, Modelo, Renavam, NumeroChassi FROM Veiculo WHERE Renavam LIKE '%"+palavraBusca+"%'";
                        } else if (radio_Chassi.isSelected()){
                            sql = "SELECT Placa, Marca, Modelo, Renavam, NumeroChassi FROM Veiculo WHERE NumeroChassi LIKE '%"+palavraBusca+"%'";
                        }
                        
                        PreparedStatement pst = con.prepareStatement(sql);
                        ResultSet rs = pst.executeQuery();
                        int i = 1;
                        while (rs.next()) {
                            DefaultTableModel modeloAux = (DefaultTableModel) tabelaVeiculos.getModel();
                            modeloAux.addRow(new Object[]{i, rs.getString("Placa"), rs.getString("Marca"), rs.getString("Modelo"), rs.getString("Renavam"), rs.getString("NumeroChassi")});
                            i++;
                        }
                    }
                    
                    if (tabelaVeiculos.getRowCount() == 0) {
                        JOptionPane.showMessageDialog(null, "A pesquisa não encontrou nenhum veículo.");
                    }
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um filtro de busca.");
        }
    }
    
    public void veiculoBuscaTodos(){
        limpaTabelaVeiculos();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = SQL_URL.getUrl();
            try (Connection con = DriverManager.getConnection(url)) {
                String sql = "SELECT * FROM Veiculo";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                int i = 1;
                while (rs.next()) {
                    DefaultTableModel modeloAux = (DefaultTableModel) tabelaVeiculos.getModel();
                    modeloAux.addRow(new Object[]{i, rs.getString("Placa"), rs.getString("Marca"), rs.getString("Modelo"), rs.getString("Renavam"), rs.getString("NumeroChassi")});
                    i++;
                }
                if (tabelaVeiculos.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "A pesquisa não encontrou nenhum veículo.");
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void limpaTabelaVeiculos(){
        int rowCount = tabelaVeiculos.getRowCount();
        if (rowCount > 0) {
            while (rowCount > 0) {
                ((DefaultTableModel) tabelaVeiculos.getModel()).removeRow(rowCount - 1);
                rowCount--;
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnVisualizacao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JRadioButton radio_Chassi;
    private javax.swing.JRadioButton radio_Marca;
    private javax.swing.JRadioButton radio_Modelo;
    private javax.swing.JRadioButton radio_Placa;
    private javax.swing.JRadioButton radio_Renavam;
    private javax.swing.JTable tabelaVeiculos;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the veiculoController
     */
    public VeiculoController getVeiculoController() {
        return veiculoController;
    }

    /**
     * @param veiculoController the veiculoController to set
     */
    public void setVeiculoController(VeiculoController veiculoController) {
        this.veiculoController = veiculoController;
    }

    /**
     * @return the veiculoAux
     */
    public Veiculo getVeiculoAux() {
        return veiculoAux;
    }

    /**
     * @param veiculoAux the veiculoAux to set
     */
    public void setVeiculoAux(Veiculo veiculoAux) {
        this.veiculoAux = veiculoAux;
    }

    /**
     * @return the criarVeiculo
     */
    public CriarVeiculo getCriarVeiculo() {
        return criarVeiculo;
    }

    /**
     * @param criarVeiculo the criarVeiculo to set
     */
    public void setCriarVeiculo(CriarVeiculo criarVeiculo) {
        this.criarVeiculo = criarVeiculo;
    }

    /**
     * @return the editarVeiculo
     */
    public EditarVeiculo getEditarVeiculo() {
        return editarVeiculo;
    }

    /**
     * @param editarVeiculo the editarVeiculo to set
     */
    public void setEditarVeiculo(EditarVeiculo editarVeiculo) {
        this.editarVeiculo = editarVeiculo;
    }

    /**
     * @return the visualizarVeiculo
     */
    public VisualizarVeiculo getVisualizarVeiculo() {
        return visualizarVeiculo;
    }

    /**
     * @param visualizarVeiculo the visualizarVeiculo to set
     */
    public void setVisualizarVeiculo(VisualizarVeiculo visualizarVeiculo) {
        this.visualizarVeiculo = visualizarVeiculo;
    }
}
